---
sidebar: sidebar 
permalink: Reference.Release_Notes.vds_v5.3_release_notes.html 
summary: ネットアップ VDS リリースノート v5.3 
keywords:  
---
= Virtual Desktop Service –バージョン 5.3



NOTE: v5.3 of VDS については、今後のリリースで繰り返し発生することはありません。すべてのリリースがホットフィックスとみなされます。



== VDS 5.3 リリース： Thurs. 、 2020 年 12 月 17 日

_Components ： _5.3 Virtual Desktop Service_When ： _ Thursday December 17,2022:00 ～ 23:00 Eastern _ Impact ： _ エンドユーザのデスクトップおよびアプリケーションサービスへのアクセスは中断されません。仮想デスクトップサービスへのアクセスは引き続き可能です。


NOTE: 次のリリースサイクルは、 2021 年 1 月 7 日（木）に、 2020 年大晦日の代わりに開始されます。



=== Virtual Desktop Service の略

* Postmark を利用するように SMTP サービスを更新します




== VDS 5.3 リリース： Thurs. 、 2020 年 10 月 22 日

_ コンポーネント： _5.3 仮想デスクトップサービス _ 日付： 2020 年 10 月 22 日午後 10 時 ～ 午後 11 時（ Eastern _Impact ）： _ エンドユーザ向けのデスクトップおよびアプリケーションサービスへのアクセスは中断されません。仮想デスクトップサービスへのアクセスは引き続き可能です。



=== VDS

* MFA エージェントが従来の IIT 命名規則を使用するフォルダに存在するシナリオに対するバグ修正




== VDS 5.3 リリース： Thurs. 、 2020 年 10 月 8 日

_ コンポーネント： _5.4 仮想デスクトップサービス _ 日付： 2020 年 10 月 8 日午後 10 時 ～ 午後 11 時（ Eastern _Impact ）： _ エンドユーザ向けのデスクトップおよびアプリケーションサービスへのアクセスは中断されません。仮想デスクトップサービスへのアクセスは引き続き可能です。



=== VDS

* Provisioning Collections のバグ修正–ハイパーバイザーテンプレートが自動選択されていません




== VDS 5.3 リリース： Thurs. 、 2020 年 9 月 10 日

_ コンポーネント： _5.3 仮想デスクトップサービス _ 日付： 2020 年 9 月 10 日午後 10 時から午後 11 時に終了： _ エンドユーザのデスクトップおよびアプリケーションサービスへのアクセスは中断されません。仮想デスクトップサービスへのアクセスは引き続き可能です。



=== Virtual Desktop Service の略

* Azure テンプレートのリストを返すために使用する API 呼び出しの数を減らしてください
* サーバリソースの参照リンクの更新 ( 夜間レポート
* AD で強化されたスリムな権限セットをサポートするように管理パスワードを変更する修正




== VDS 5.3 リリース： Thurs. 、 2020 年 8 月 27 日

_ コンポーネント： _5.3 仮想デスクトップサービス _ 日付： 2020 年 8 月 13 日（木）午後 10 時 ～ 午後 11 時（東部標準時）： _ エンドユーザのデスクトップおよびアプリケーションサービスへのアクセスは中断されません。仮想デスクトップサービスへのアクセスは引き続き可能です。



=== Virtual Desktop Service の略

* 日付と時刻の情報が現在の日付と時刻として表示されていたスクリプトイベントシナリオのバグ修正




=== Azure コスト試算ツール

* Azure Hybrid の機能のリリース
* VM の詳細にカスタム名情報を入力する際の DISPLAY 問題のバグ修正




== VDS 5.3 リリース： Thurs. 、 2020 年 8 月 13 日

_ コンポーネント： _5.3 仮想デスクトップサービス _ 日付： 2020 年 8 月 13 日（木）午後 10 時 ～ 午後 11 時（東部標準時）： _ エンドユーザのデスクトップおよびアプリケーションサービスへのアクセスは中断されません。仮想デスクトップサービスへのアクセスは引き続き可能です。



=== Azure コスト試算ツール

* エフェメラル OS ディスクのサポートを追加します
* ストレージ選択に関するツールヒントが改善されました
* ユーザが負のユーザ数を入力できるようになったシナリオを禁止します
* AVD とファイルサーバーの両方の選択を使用する場合は、ファイルサーバーを表示します




== VDS 5.3 リリース： Thurs. 、 2020 年 7 月 30 日

_ コンポーネント： _5.3 仮想デスクトップサービス _ 日付： 2020 年 7 月 30 日（木）午後 10 時 ～ 午後 11 時（東部標準時）： _ エンドユーザのデスクトップおよびアプリケーションサービスへのアクセスは中断されません。仮想デスクトップサービスへのアクセスは引き続き可能です。



=== Virtual Desktop Service の略

* AVD Diagnostics が正しく表示されなかったシナリオのサブセットのバグ修正




=== Azure コスト試算ツール

* お客様のデータが高可用性である必要があるかどうかを確認し、必要に応じて、 Azure NetApp Files のような PaaS サービスを活用してコストと人件費の節約を利用できるかどうかを定義します
* AVD と RDS の両方のワークロードに対するデフォルトのストレージタイプを Premium SSD にアップデートし、標準化する
* バックグラウンドでパフォーマンスが強化されました




== VDS 5.3 リリース： Thurs 、 2020 年 7 月 16 日

_ コンポーネント： _5.3 仮想デスクトップサービス _ 日付： 2020 年 7 月 16 日（木）午後 10 時 ～ 午後 11 時（東部標準時）： _ エンドユーザのデスクトップおよびアプリケーションサービスへのアクセスは中断されません。仮想デスクトップサービスへのアクセスは引き続き可能です。



=== Virtual Desktop Service の略

* プロアクティブなセキュリティ強化
* ワークスペースモジュールのパフォーマンスが改善されました。これは、 [ ユーザーとグループ ] タブの下にあるページグループを作成することによって実現します




=== VDS セットアップ

* 新しい自動化オプションが利用可能になったときに、 Azure Active Directory ドメインサービス（ AADDS ）を選択して Standard サービス階層を確実に使用できるようにするための更新が行われました
* Microsoft ARM API 呼び出しへの変更を反映するための更新




=== HTML5 ログインエクスペリエンス

* ネットアップのブランド力やフレージングを反映するように更新されました




=== Azure コスト試算ツール

* 地域ごとに価格を動的に表示します
* リージョン内で関連サービスが利用可能かどうかを表示し、必要な機能がそのリージョンで利用可能になるかどうかをユーザが理解できるようにします。これらのサービスは次のとおりです。
* Azure NetApp Files の特長
* Azure Active Directory ドメインサービス
* NV および NV v4 （ GPU 対応）仮想マシン




== VDS 5.3 リリース： Thurs. 、 2020 年 6 月 25 日

_ コンポーネント： _5.3 仮想デスクトップサービス _ 日付： 2020 年 6 月 25 日（木）午後 10 時 ～ 午後 11 時（東部標準時）： _ エンドユーザのデスクトップおよびアプリケーションサービスへのアクセスは中断されません。仮想デスクトップサービスへのアクセスは引き続き可能です。



=== Virtual Desktop Service の略

* ネットアップのブランド力やフレージングを反映するように更新されました
* ユーザのリストが想定どおりに読み込まれなかった独立したシナリオのバグ修正
* 手動での導入が部分的にしか修正されていない GPO 構成を受け取ったシナリオのバグ修正




=== VDS セットアップウィザード

* American Express のサポート
* ネットアップのブランド力やフレージングを反映するように更新されました




=== REST API

* リストデータの収集と表示を高速化する継続的な機能強化




== VDS 5.3 リリース： Thurs. 、 2020 年 6 月 11 日

_ コンポーネント： _5.3 仮想デスクトップサービス _ 日付： 2020 年 6 月 11 日（木）午後 10 時 ～ 午後 11 時（東部標準時）： _ エンドユーザのデスクトップおよびアプリケーションサービスへのアクセスは中断されません。仮想デスクトップサービスへのアクセスは引き続き可能です。



=== Virtual Desktop Service の略

* プロアクティブな API 処理の強化
* プラットフォーム要素の予防的な強化




=== クラウドワークスペースツールとサービス

* ライブスケーリングのトリガーに対する継続的な改善
* vCloud から vSphere への導入時に特定された問題の自動修正機能が強化されました




== VDS 5.3 ホットフィックス : Thurs.2020年5月

_Components ： _5.3 Virtual Desktop Service_When ： _ 水曜日 6 月 3 日午前 10 時 ～ 10 時 30 分 Eastern _Impact ： _ エンドユーザのデスクトップおよびアプリケーションサービスへのアクセスは中断されません。仮想デスクトップサービスへのアクセスは引き続き可能です。



=== クラウドワークスペースツールとサービス

* プラットフォーム導入の自動化された要素のバグ修正。これは新規の導入にのみ適用され、既存の導入環境には影響しません。
* 既存の Active Directory 構造への展開に関するバグ修正




== VDS 5.3 リリース： Thurs. 、 2020 年 5 月 28 日

_ コンポーネント： _5.3 仮想デスクトップサービス _ 日付： 2020 年 5 月 28 日（木）午後 10 時 ～ 午後 11 時（東部標準時）： _ エンドユーザのデスクトップおよびアプリケーションサービスへのアクセスは中断されません。仮想デスクトップサービスへのアクセスは引き続き可能です。



=== Virtual Desktop Service の略

* ネットアップのブランド力やフレージングを反映するように更新されました
* Workspace モジュールのパフォーマンスの向上
* プロアクティブな安定性の強化：よく使用される API 呼び出しを基盤とする VDS 機能




=== 仮想デスクトップサービスの導入

* VDS プラットフォームの設置面積を Azure 環境でさらに合理化
* 既存の Active Directory 構造に展開する際のオプションシナリオのバグ修正




=== Virtual Desktop Service のツールとサービス

* サーバーにログインしているユーザー数をライブスケーリングで識別する方法に対する継続的な改善




=== Virtual Desktop Service Web Client の略

* ネットアップのブランド力やフレージングを反映するようにブランディングを更新しました
* デフォルトの Web Client リンクよりも長いお気に入りとして保存された URL の短縮のサポート（ cloudworkspace.com/login/ から cloudworkspace.com など）




=== Azure コスト試算ツール

* SQL Server のオプションを追加して、 VM のシリーズやサイズを増やします
* IP アドレスの価格設定の表示方法を更新します。 IP アドレスを追加しない限り、 IP アドレスのコストを表示しないでください




== CWMS 5.3 リリース： Thurs 、 2020 年 5 月 14 日

_ コンポーネント： _5.3 Cloud Workspace Management Suite_When ： _ 木曜日は 2020 年 5 月 14 日午後 10 時 ~ 午後 11 時に、 Eastern _ Impact ： _ エンドユーザー向けのクラウドワークスペースデスクトップおよびアプリケーションサービスへのアクセスは中断されません。Cloud Workspace Management Suite へのアクセスは引き続き可能です。



=== Azure コスト試算ツール

* ネットアップのブランド / フレージングを反映してメッセージを更新
* プラットフォームサーバーを更新して、 D2S v3 の使用を反映させました
* Windows 10 Enterprise E3 ライセンスの詳細と価格を更新
* デフォルトのストレージ選択を Azure NetApp Files に変更します




== CWMS 5.3 Hotfix : Thurs.2020年5月

_ コンポーネント： _5.3 Cloud Workspace Management Suite_When ： _ 金曜日 2020 年 5 月 8 日午前 10 時 15 分 ~ 午前 10 時 30 分 Eastern _Impact ： _ エンドユーザー向けのクラウドワークスペースデスクトップおよびアプリケーションサービスへのアクセスは中断されません。Cloud Workspace Management Suite へのアクセスは引き続き可能です。



=== クラウドワークスペースツールとサービス

* 導入プロセス中に特定の組み合わせの設定に対して DNS レコードが設定されるメソッドのバグ修正




== CWMS 5.3 リリース： Thurs 、 2020 年 4 月 30 日

_ コンポーネント： _5.3 Cloud Workspace Management Suite_ 日付： 2020 年 4 月 30 日（木）午後 10 時 ～ 午後 11 時（東部標準時）： _ エンドユーザー向けのクラウドワークスペースデスクトップおよびアプリケーションサービスへのアクセスは中断されません。Cloud Workspace Management Suite へのアクセスは引き続き可能です。



=== Cloud Workspace Management Suite の略

* セッショントラッキングを改善して、将来の更新を可能にする–将来の機能をプレビューするオプション
* スクリプト化されたイベントを更新して ' アプリケーションとアクティビティの柔軟性を向上させます
* Provisioning Collections 設定の特定の組み合わせに対するバグ修正




=== クラウドワークスペースツールとサービス

* AVD ホストプールごとにワークロードスケジューリングを設定できるようにします
* 既存の AD 構造への新規導入の作成プロセスが改善されました
* Azure Files を使用している組織にデータパス、ホームパス、プロファイルデータパスを割り当てる機能を有効にします
* リソースプールを管理する機能を有効にします
* 導入ウィザードでの特殊文字の処理が改善されました
* RDS （ AVD ではない）ワークロードの導入の一環として、自動化された HTML5 コンポーネントに対する調整




=== REST API

* 導入可能な Azure リージョンのリストが更新されました
* TSData の役割を持つサーバの Azure Backup 統合の処理が改善されました
* ログインに失敗した場合にログイン試行が 2 回失敗するシナリオの一部で、問題を解決します




=== CWA 設定

* Azure のベストプラクティスに従って、サブネット IP の詳細がプライベート IP アドレス範囲内にあるようにします。受け入れられるプライベート IP 範囲は次のとおりです。
+
** 192.168.0.0 ～ 192.168.255.255
** 172.16.0.0 ～ 172.31.255.255
** 10.0.0.0 ～ 10.255.255.255






=== HTML5 ログインエクスペリエンス

* の機能強化をホストするバックグラウンド処理 https://login.cloudworkspace.com[] および https://login.cloudjumper.com[]。注：カスタムブランドの HTML5 ログインポータルには影響はありません。
* セルフサービスパスワードリセットが表示されなかったシナリオの一部に対するバグ修正




== CWMS 5.3 Hotfix ： Wedn 。2020年4月

_ コンポーネント： _5.3 Cloud Workspace Management Suite_When ： _ 水曜日 2020 年 4 月 22 日午後 10 時 ~ 午後 11 時にイースタン _ インパクト： _ エンドユーザー向けのクラウドワークスペースデスクトップおよびアプリケーションサービスへのアクセスは中断されません。Cloud Workspace Management Suite へのアクセスは引き続き可能です。



=== Cloud Workspace Management Suite の略

* パフォーマンスアップグレードにより、お客様の使用量の増加に対応




== CWMS 5.3 リリース： Thurs 、 2020 年 4 月 16 日

_ コンポーネント： _5.3 Cloud Workspace Management Suite_When ： _ 木曜日 2020 年 4 月 16 日午後 10 時 ~ 午後 11 時にイースタン _ インパクト： _ エンドユーザー向けのクラウドワークスペースデスクトップおよびアプリケーションサービスへのアクセスは中断されません。Cloud Workspace Management Suite へのアクセスは引き続き可能です。



=== Cloud Workspace Management Suite の略

* AVD ホストプール VM の作成検証が継続的に強化されている（ COVID-19 による Azure アクティビティの急増が原因で Azure のプロセス時間が考慮される）
* AVD 初期化時の AVD の安定性の向上– AVD テナント名が AVD にグローバルに固有でない場合、 CloudJumper は、展開 / テナントに固有の更新された文字列に置き換えられます。
* CWMS パスワードリセット機能では、電子メールアドレスに特殊文字のサポートを含めることができます
* AVD RemoteApp グループにアプリケーションを追加するときに、一部のシナリオのバグ修正が [ スタート ] メニューからアプリケーションをプルしませんでした
* ユーザアクティビティレポートのサブセットに対するバグ修正
* AVD ホストプールの概要の要件を削除します（オプションフィールドおよびそのまま）。
* 共有ホストプール内の VM が VDI VM としてタグ付けされた単一フリンジのシナリオに対するバグ修正




=== CWA 設定

* Distributor ワークフローのオーダーコードの追加サポート




=== クラウドワークスペースツールとサービス

* Solarwinds Orion RMM ツールで管理される VM の管理を停止する機能が強化され、ワークロードスケジューリングに対応しました




== CWMS 5.3 リリース： Thurs 、 2020 年 4 月 2 日

_ コンポーネント： _5.3 Cloud Workspace Management Suite_When ： _ 木曜日 2020 年 4 月 2 日午後 10 時 ~ 午後 11 時にイースタン _ インパクト： _ エンドユーザー向けのクラウドワークスペースデスクトップおよびアプリケーションサービスへのアクセスは中断されません。Cloud Workspace Management Suite へのアクセスは引き続き可能です。



=== Cloud Workspace Management Suite の略

* アクティビティ履歴：日付のローカライズによって一部のアクティビティ履歴が CWMS に表示されない地域展開のディスプレイ問題を解決します
* 画像のサイズを問わないコレクション拡張をプロビジョニングします
* Azure テナント内の AADDS の複数のドメインに対するバグ修正–新しく作成されたユーザーは、 Workspace のログイン ID を照合するのではなく、以前にプライマリ Azure ドメインを使用していました
* ユーザ名の更新時のアクティビティ履歴のバグ修正–機能は正常に動作していますが、以前のユーザ名は正しく表示されませんでした




=== CWA 設定

* 登録時に使用される CWMS アカウントでの MFA の処理が改善されました
* 導入時に適用される権限が少なくなりました




=== クラウドワークスペースツールとサービス

* 継続的なサービス / 自動化に必要な権限の削減
* CWMGR1 でのリソース消費を削減するためのプロセス強化




=== REST API

* ユーザ名の更新時のアクティビティ履歴のバグ修正




== CWMS 5.3 Hotfix ： Tues.2020年3月

_ コンポーネント： _5.3 Cloud Workspace Management Suite_When ： _ 2020 年 3 月 24 日（火）午後 10 時 ～ 午後 11 時にイースタン _ インパクト： _ エンドユーザー向けのクラウドワークスペースデスクトップおよびアプリケーションサービスへのアクセスは中断されません。Cloud Workspace Management Suite へのアクセスは引き続き可能です。



=== Azure コスト試算ツール

* AVD ユーザータイプの概要と、 Microsoft のドキュメントに従って実行されるプログラムを更新
* CWMS ライセンスの明確性が向上しました




=== CWMS 5.3 リリース： Thurs 、 2020 年 3 月 19 日

_ コンポーネント： _5.3 Cloud Workspace Management Suite_When ： _ 木曜日 2020 年 3 月 19 日午後 10 時 ~ 午後 11 時 Eastern _Impact ： _ エンドユーザー向けのクラウドワークスペースデスクトップおよびアプリケーションサービスへのアクセスは中断されません。Cloud Workspace Management Suite へのアクセスは引き続き可能です。



=== Cloud Workspace Management Suite の略

* 複数サイトへの展開のためのサーバ拡張機能への接続 - CWMS 管理者が接続しているサイトを自動的に検出し、接続を処理します
* 移行モードを有効にすると、ライブスケーリングが無効になります
* 既存のクライアントで新しい Cloud Workspace Services を有効にするためのバグ修正




=== CWA 設定

* 導入ウィザードの機能強化が裏で行われました




== CWMS 5.3 リリース： Thurs 、 2020 年 3 月 5 日

_ コンポーネント： _5.3 Cloud Workspace Management Suite_When ： _ 木曜日 2020 年 3 月 5 日午後 10 時 ~ 午後 11 時 Eastern _Impact ： _ エンドユーザー向けのクラウドワークスペースデスクトップおよびアプリケーションサービスへのアクセスは中断されません。Cloud Workspace Management Suite へのアクセスは引き続き可能です。



=== Cloud Workspace Management Suite の略

* Master Client レポートのパフォーマンス向上
* 正しく作成されなかった VM から削除機能を削除します。これは、作成されていない VM は削除できないためです




=== クラウドワークスペースツールとサービス

* DC Config 設定が適切に構成されていないマルチサイト環境を正常に処理するためのバグ修正
* vSphere サイトのリソース割り当てタイプが Fixed に設定されているマルチサイト環境のバグ修正




=== HTML 5 ポータル

* AVD 資格情報を使用してログインするユーザーのプロセス拡張機能




=== Azure コスト試算ツール

* ライブスケーリングのための明確な改善
* Microsoft AVD メッセージングに合わせた調整
* ワークロードのスケジューリングおよびライブスケーリングの削減の詳細に関するバグ修正。大幅にカスタマイズされた見積もりに含まれます




== CWMS 5.3 リリース： Thurs. 、 2020 年 2 月 20 日

_ コンポーネント： _5.3 Cloud Workspace Management Suite_When ： _ 木曜日 2020 年 2 月 20 日午後 10 時 ~ 午後 11 時 Eastern _Impact ： _ エンドユーザー向けのクラウドワークスペースデスクトップおよびアプリケーションサービスへのアクセスは中断されません。Cloud Workspace Management Suite へのアクセスは引き続き可能です。



=== Cloud Workspace Management Suite の略

* ワークスペースモジュールの VM リソースタブで SDDC を配置に切り替えます




=== CWA 設定

* 導入中にポリシーを適用するプロセスを合理化
* Azure Active Directory ドメインサービスを使用した新規導入に対するセキュリティの強化
* 新しい導入のセキュリティを強化–導入時に（フラットサブネットではなく）サブネットの分離を定義する必要があります
* ThinPrint ライセンスを適用する際の RDS （非 AVD ）展開のバグ修正
* ThinPrint が DC Config にインストールされているかどうかを適切に処理するためのバグ修正
* FTP 機能の利用を選択する組織の追加のチェックと検証




=== クラウドワークスペースツールとサービス

* 複数のサイトを含む導入環境に誤って設定されたサイトがある場合の自動化されたアクションのバグ修正
* VM を削除してもバックグラウンドで VM が正しく消去されないインスタンスのバグ修正
* DC Config でハイパーバイザー接続をテストする際の機能の改善とバグ修正




=== REST API

* 組織のユーザーのリストを表示する際のパフォーマンスの向上
* 組織のアプリケーションのリストを表示する際のパフォーマンスの向上
* AVD アプリケーショングループにユーザーを追加する際の機能強化：
* 425 にインポートするユーザーの数を制限します
* 425 ユーザを超えるユーザをインポートしようとする場合は、最初の 425 ユーザのインポートに進み、ユーザインポートに対する AVD の制限が 425 であることを表示し、 5 分以内に追加のインポートを続行できることを確認します
* グループ内のユーザーの数が、グループ内のユーザーの総数とは対照的に、グループ内のクラウドワークスペースユーザーの数であることを反映するために更新します（既存の Active Directory 構造に展開する場合は少なくなることがあります）。
* グループのメンバーである名前付きユーザーのセキュリティグループを使用して、アプリケーションの割り当てを有効にします（ネストされたグループは、アプリケーションの割り当てを受け取りません）。




=== Azure コスト試算ツール

* ユーザーが支援を依頼できるように、ページの下部にリンクを追加します
* Premium レベルのデフォルトの Azure NetApp Files
* プレミアム SSD をファイルサーバーストレージタイプの選択肢に追加します
* Azure Active Directory ドメインサービスのテキストを更新– AADDS から Azure AD ドメインサービスに変更
* Active Directory のテキストの更新– Windows Active Directory VM から Windows Server Active Directory に変更します




== CWMS 5.3 Hotfix ： Thurs 、 2020 年 2 月 13 日

_Components ： _5.3 Cloud Workspace Management Suite_When ： _ Thursday February 13 、 2020 年 2 月 13 日午後 10 時 ~ 午後 11 時 Eastern _Impact ： _ エンドユーザー向けのクラウドワークスペースデスクトップおよびアプリケーションサービスへのアクセスは中断されません。Cloud Workspace Management Suite へのアクセスは引き続き可能です。



=== Azure コスト試算ツール

* 一部のシナリオで E シリーズ VM を使用する際の価格設定エラーに対するバグ修正




== CWMS 5.3 リリース： Thurs. 、 2020 年 2 月 6 日

_ コンポーネント： _5.3 Cloud Workspace Management Suite_When ： _ Thursday February 6 、 2020 年 2 月 6 日午後 10 時 ~ 午後 11 時 Eastern _Impact ： _ エンドユーザー向けのクラウドワークスペースデスクトップおよびアプリケーションサービスへのアクセスは中断されません。Cloud Workspace Management Suite へのアクセスは引き続き可能です。



=== Cloud Workspace Management Suite の略

* VM 作成プロセスのプロビジョニングステータスの詳細が改善されました
* AVD ホストプールの一部である、新しく作成されたセッションホスト VM の自動化処理の改善
* 「サーバアクセスユーザのみ」を含む場合のユーザアクティビティレポートのパフォーマンスの向上




=== クラウドワークスペースツールとサービス

* 管理者が従来の（ Azure 以外の） Active Directory のユーザアカウントを手動で編集する際のデータパス管理のバグ修正
* 微妙なシナリオにおけるワークロードスケジューリングの安定性が向上しました




=== Azure コスト試算ツール

* ワークロードスケジューリングとライブスケーリングによって達成された具体的な削減について、別々に説明します組み合わせ（ Combined ）
* Premium （ SSD ）ストレージをサポートするために、サーバの「 S 」バージョンを表示します
* 印刷された概算見積書のレイアウトを改善
* SQL Server の価格が正しく計算されなかった問題のバグ修正




== CWMS 5.3 リリース： Thurs 、 2020 年 1 月 23 日

_ コンポーネント： _5.3 Cloud Workspace Management Suite_When ： _ Thursday January 23 、 2020 年 1 月 23 日午後 10 時 ~ 午後 11 時 Eastern _ Impact ： _ エンドユーザー向けのクラウドワークスペースデスクトップおよびアプリケーションサービスへのアクセスは中断されません。Cloud Workspace Management Suite へのアクセスは引き続き可能です。



=== Cloud Workspace Management Suite の略

* 古いをリダイレクトします https://iit.hostwindow.net[] 近代的なホテル https://manage.cloudworkspace.com[]
* IE 11 経由でログインしている CWMS 管理者のサブセットに関するバグ修正
* API ユーザを削除すると、そのユーザはバックグラウンドで正しく削除されますが、 CWMS では削除済みと表示されていなかったビジュアル問題を修正します
* サブスクリプションをクリアするプロセスを合理化して ' 新しい / テスト環境を再プロビジョニングできます
* サービスボードの機能強化–アプリケーションのショートカットに使用するアイコンがオンラインになっているセッションホストサーバーのみを確認します




=== クラウドリソースアプリケーション

* コマンドラインを使用した OU または Active Directory セキュリティグループからのユーザのインポートをサポートします




=== クラウドワークスペースツールとサービス

* ライブスケーリングの拡張機能がバックグラウンドで強化されました




=== CWA 設定

* CWA セットアッププロセスで使用されるアカウントに MFA が適用されている場合のシナリオの処理が改善されました




=== Azure コスト試算ツール

* VM のサイズ設定をデフォルトで更新して、 Microsoft の推奨事項を反映させます




== CWMS 5.3 リリース： Thurs 、 2020 年 1 月 9 日

_ コンポーネント： _5.3 Cloud Workspace Management Suite_When ： _ Thursday January 9 、 2020 年 1 月 9 日午後 10 時 ~ 午後 11 時 Eastern _Impact ： _ エンドユーザー向けのクラウドワークスペースデスクトップおよびアプリケーションサービスへのアクセスは中断されません。Cloud Workspace Management Suite へのアクセスは引き続き可能です。



=== Cloud Workspace Management Suite の略

* 電子メール管理者のフレージングの更新は、更新されたリンクを反映するために新しいワークスペースを作成した後に受信されます
* 一連のフォルダ権限エラーが存在する場合、サーバーがサーバーリストに表示されていなかった問題のバグ修正
* CWMGR1 の Resource Pools テーブルにリソースプールが存在しない場合、サーバのバグ修正は Servers リストに表示されませんでした




=== クラウドリソースアプリケーション

* Active Directory セキュリティグループからのユーザのインポートをサポートします。
* 検証機能の強化：コマンドラインの引数 / サーバに適切なコマンドラインパラメータを使用していることを確認します
* 検証機能の強化：コマンドラインからインポートする際に、重複するユーザーをチェックします
* 検証機能の強化：コマンドラインからインポートするときに指定したサイトにインポートするサーバが属していることを確認します




=== REST API

* セキュリティ機能の強化が舞台裏で追加されています




=== クラウドワークスペースツールとサービス

* コマンド処理の安定性が向上しました
* ワークロードのスケジューリングとライブスケーリングの強化
* ワークロードのスケジュール設定と、バックグラウンドでのライブスケーリングの安定性が向上します
* 新しい展開における FSLogix の更新と機能強化：ダウンロードとお気に入りをプロファイルコンテナにリダイレクトして、ベストプラクティスに一致させます
* ホストプール VM の作成の安定性がさらに強化されています
* 新しいサイトのゲートウェイを指定できるようになります
* VM の自動検証機能が向上
* 自動化されたデータベース管理の向上
* VM の電源がオフになったときに同じ操作が実行されるようになったため、ユーザ作成処理の効率が向上しました
* Microsoft Azure 環境での一時ディスクの処理が合理化されました
* GCP 展開のリソース割り当てタイプの処理が改善されました
* ProfitBricks データセンターのドライブ拡張に関するバグ修正
* App Services ベースのクライアント作成の安定性が向上しました
* サーバをあるロールから別のロールに変換した後のバグ修正と安定性の向上




== CWMS 5.3 リリース： 2019 年 12 月 20 日（金

_ コンポーネント： _5.3 Cloud Workspace Management Suite_ 日付： _ 金曜日 2019 年 12 月 20 日午後 10 時 ~ 午後 11 時（ Eastern _Impact ）： _ エンドユーザー向けのクラウドワークスペースデスクトップおよびアプリケーションサービスへのアクセスは中断されません。Cloud Workspace Management Suite へのアクセスは引き続き可能です。



=== クラウドワークスペースツールとサービス

* ユーザアクティビティのロギングでデータが正常に記録されないシナリオを修正しました




== CWMS 5.3 リリース： Thurs. 、 2019 年 12 月 19 日

_ コンポーネント： _5.3 Cloud Workspace Management Suite_When ： _ Thursday December 19 （ 2019 年 12 月 19 日午後 10 時 ～ 午後 11 時）： _ エンドユーザー向けのクラウドワークスペースデスクトップおよびアプリケーションサービスへのアクセスは中断されません。Cloud Workspace Management Suite へのアクセスは引き続き可能です。



=== Cloud Workspace Management Suite の略

* CWMS 可用性モニタリングの改善
* AVD アプリケーショングループのユーザーモーダルを使用した問題の場合、大文字が含まれていると、ユーザー名が正しく選択されないことがあります
* 「 User Support Only 」管理者ロールメンバーのユーザリストのページ付けを修正しました
* MFA セットアップダイアログでラジオボタンの配置を修正
* サービスボードの依存関係を削除することで、ダッシュボード / 概要ページのロードが改善されました
* 管理者ユーザーが管理者権限を持っていない場合、自分のパスワードをリセットできない問題の修正
* 将来のトラブルシューティングのためにデバッグログを収集する機能が改善され




=== クラウドリソースアプリケーション

* 機能拡張： AD グループメンバーシップに基づいてユーザのインポートを許可します。
* 機能拡張：インポート時にデフォルトのログオン識別子を指定できるようにします




=== Azure コスト試算ツール

* VM 下のストレージに関するテキストとツールチップを改善する




=== CWA 設定

* 導入ワークフローが改善されました




=== クラウドワークスペースツールとサービス

* 新しいユーザ作成時のデータサーバのロック処理の改善
* ワークロードのスケジュール設定中に、クライアントにキャッシュ会社として誤ったフラグが設定される状況を修正しました
* ワークスペースなしで組織が作成されたときに会社テーブルを正しく更新する修正
* ローカルコントロールプレーンデータベース内の AVD ホストプール名に付加された無効な文字の修正
* ワークロードのスケジュール設定を使用した問題に対して、 VM がローカルのコントロールプレーンデータベースに表示され、ハイパーバイザーに表示されないように修正しました
* 一部の VM のドライブが Azure ハイパーバイザーで自動的に拡張されないように、問題を修正しました
* クライアントプロビジョニングエラー「 upplied data drive not valid 」の修正
* 特定のシナリオで CWAgent のインストールに失敗した場合の修正
* TestVDCTools の改善により、新しいサイトの作成時に RDS ゲートウェイ URL を割り当てることが可能になりました
* 「 disabled 」に設定されている一部のシナリオで、ワークロードのスケジューリングエラーが修正されました
* キャッシュ内にサーバーがまだ存在する場合の問題を修正しました
* ドライブの自動拡張後に一部の VM の電源投入に失敗した場合の修正
* Azure NetApp Files で Azure ファイルまたは問題を使用する際のフォルダ / 権限の管理に関する問題が修正されました




== CWMS 5.3 リリース : Mon.2019年12月

_ コンポーネント： _5.3 Cloud Workspace Management Suite_When ： _ 月曜、 2019 年 12 月 2 日午後 10 時 ~ 午後 11 時、 Eastern _ Impact ： _ エンドユーザー向けのクラウドワークスペースデスクトップおよびアプリケーションサービスへのアクセスは中断されません。Cloud Workspace Management Suite へのアクセスは引き続き可能です。



=== Cloud Workspace Management Suite の略

* FSLogix の自動インストールに対する機能強化
* ライブスケーリングの更新と修正
* CWMS のドロップダウンリストに AMD （ GPU 以外の） VM を追加します
* 同じ AVD 環境で複数のテナントをサポート




=== CWA 設定

* CWA 設定のヘルプ / サポートセクションでの明確な改善




=== Azure コスト試算ツール

* 見積もりに Microsoft ライセンスを含まないことを選択したシナリオのバグ修正が引き続き含まれます




=== クラウドリソースアプリケーション

* データセンターサイトのコマンドライン機能を使用する際の追加の検証
* 新しいコマンドライン引数– /listserversinsite
* 設定の拡張–会社をインポートするときに、サイトに設定されている RDSH ゲートウェイを使用するように RDSH 展開を設定します




=== クラウドワークスペースツールとサービス

* DC 構成の vCloud サポート要素を更新しました
* より具体的なシナリオでサーバタイプを正しく検出するための TestVDCTools の機能強化




== CWMS 5.3 リリース： Thurs. 、 2019 年 11 月 14 日

_ コンポーネント： _5.3 Cloud Workspace Management Suite_When ： _ Thursday November 14 、 2019 年 11 月 14 日午後 10 時 ~ 午後 11 時 Eastern _Impact ： _ エンドユーザ向けのクラウドワークスペースデスクトップおよびアプリケーションサービスへのアクセスは中断されません。Cloud Workspace Management Suite へのアクセスは引き続き可能です。



=== Cloud Workspace Management Suite の略

* 冗長性と高可用性がバックグラウンドで追加されています
* CWMS のドロップダウンメニューが検索可能になります
* ワークスペースモジュール使用時のパフォーマンスの向上
* ワークスペースモジュールのサーバーセクションを使用した場合のパフォーマンスの向上
* ワークスペースモジュールのサーバーセクションにホストプール名を表示します
* ワークスペースモジュールのサーバーセクションがページ設定され、一度に 15 台のサーバーが表示されます
* バグ修正：一部の管理者が新しいホストプールを作成しても VM テンプレートが表示されないシナリオ
* ホストプールに移動するシナリオのバグ修正では、 2 番目のホストプールに最初のホストプールからの情報が表示される場合があります
* 管理者のサブセットが旧バージョンの CWMS にログインできなかったバグ修正
* AVD Diagnostics に移動し、ワークスペースに戻り、「ページが見つかりません」というバグ修正が表示されました
* ホストプールの名前と一致するように、ユーザのデスクトップのフレンドリ名（ AVD RDP クライアントに表示される名前と、ユーザセッションの上部にある青いバーに表示される名前）を変更します
* サーバは、デフォルトではオフになっている [ 新しいセッションを許可する ] チェックボックスを使用して、手動でプールに追加する必要があります。チェックボックスはデフォルトでオンになっています。




=== CWA 設定

* 導入環境では FSLogix が自動的に使用されるようになりました
* Azure Active Directory ドメインサービスを使用する場合は、 Data 、 Home 、 Profile ストレージのオプションのストレージターゲットとして Azure ファイルを追加します
* Azure テナントで RBAC が有効になっている場合に導入の自動化をサポートするパッケージを導入する
* 各導入環境に最新バージョンの Java および HTML5 ライセンスをインストールします
* サブネット範囲が正しく計算されなかった場合のバグ修正。導入前に検証エラーが発生しました




=== HTML5 ログインエクスペリエンス

* デフォルトのブランディングを更新して、 Cloud Workspace Client for Windows のブランディングを反映させてください。プレビューはこちらからご覧いただけます。
* 追加ブランドの HTML5 ログインページにインプレースブランディングの更新を適用します




=== Azure コスト試算ツール

* D4s v3 VM （ AVD のデフォルトの VM タイプ）のデフォルトストレージ階層を Premium SSD に更新して、 Microsoft のデフォルト設定に合わせます




=== クラウドリソースアプリケーション

* インポート時に使用する会社コードを事前に割り当てる機能を追加します




== CWMS 5.3 リリース： Thurs. 、 2019 年 10 月 31 日

_ コンポーネント： _5.3 Cloud Workspace Management Suite_ 日付： _ 木曜日 2019 年 10 月 31 日午後 10 時 ~ 午後 11 時（東部標準時）： _ エンドユーザー向けのクラウドワークスペースデスクトップおよびアプリケーションサービスへのアクセスは中断されません。Cloud Workspace Management Suite へのアクセスは引き続き可能です。



=== Cloud Workspace Management Suite の略

* iit.hostwindow.net にログインしているユーザのための更新（古いバージョンの v5.2 展開の URL は非常に少ない）は、 manage.cloudworkspace.com （ v5.3 および今後の展開の URL ）に移動するように指示するプロンプトを表示します。
* ユーザが CWMS を使用して AVD ホストプールを削除できるようにします
* 今後の CWMS でのブランディングの強化を可能にする機能強化
* VDI Provisioning Collection を検証する際の問題のバグ修正




=== Deployment Automation

* 自動化された問題解像度と、プロセスの合理化による舞台裏での改善




=== HTML5 ログインエクスペリエンス

* login.cloudjumper.com または login.cloudworkspace.com から仮想デスクトップにログインするエンドユーザに対して、一連のユーザエクスペリエンスの向上を行います。
* ユーザがアクセスできる AVD ホストプールを表示できるようにします
* 適切な権限を持つユーザーに対して Wake On Demand 機能を有効にし、 AVD セッションのホスト VM がオフラインになるようにスケジュールされているときにログインして作業できるようにします
* CWMS のユーザーアカウントに電子メールまたは電話番号が設定されているユーザーに対して、セルフサービスパスワードリセットを有効にします




=== Azure コスト試算ツール

* AD Connect のユースケースに対して AVD を選択した後、ユーザーが Windows Active Directory VM を選択できるようにします
* Microsoft のデフォルト値に合わせて、すべての VM のデフォルトのストレージ容量を 128 GB に更新します
* Microsoft のデフォルト値に合わせて、アップタイム時間のデフォルト設定を 220 に更新します
* Microsoft が変更した名前に一致するようにワークロードタイプの名前を更新します




== CWMS 5.3 リリース： Thurs. 、 2019 年 10 月 17 日

_ コンポーネント： _5.3 Cloud Workspace Management Suite_When ： _ Thursday October 17 、 2019 年 10 月 17 日午後 10 時 ~ 午後 11 時 Eastern _Impact ： _ エンドユーザ向けのクラウドワークスペースデスクトップおよびアプリケーションサービスへのアクセスは中断されません。Cloud Workspace Management Suite へのアクセスは引き続き可能です。



=== Cloud Workspace Management Suite の略

* 組織のワークスペースの OS として Server 2019 をサポートします
* AVD ホストプール内のアクティブユーザーの表示を改善するために更新します
* AVD 展開で複数の組織 / ワークスペースを許可します
* 管理者に関連付けられた複数のフィールドを編集するには、 [ 更新 ] ボタンを追加します
* 会社の詳細と連絡先情報を編集するには、 [ 更新 ] ボタンを追加します
* Flight School を使用するための検索機能が更新されました
* CWMS の下部にあるリンクを更新
* AVD 展開で検証ホストプールを使用できるようにします。これにより、 AVD 機能が GA （本番リリース）になる前に、 AVD 機能に以前からアクセスできるようになります。
* AADDS 展開で管理者が行ったアクションに応答するプロンプトで、タイプミスを修正します
* App Services の権限がない管理者への確認を求めるバグ修正




=== REST API

* 組織のワークスペースの OS として Server 2019 をサポートします
* 呼び出しがクライアントのサービスをオフラインとして返すシナリオのバグ修正




=== Deployment Automation

* データセンターサイト名の自動生成に関するバグ修正
* 要約されたログファイルと c ： \Program Files to c ： \ProgramData に移動されたログファイル




=== クラウドワークスペースツールとサービス

* Azure Shared Image Gallery からのテンプレートへのアクセスのサポート
* セキュリティの向上–ログファイルの場所を c ： \Program Files から c ： \ProgramData （また、 Microsoft の更新されたベストプラクティス）に変更することにより、管理アカウントの使用を削減する
* VDCTools でのデータセンターサイト作成の機能強化–サイトは名前にスペースを使用して作成できます
* データセンターサイトの自動作成機能の追加–アドレス範囲を自動的に選択できるようになりました
* 機能の追加–管理対象外の VHD ファイルをテンプレートとして使用するための構成オプションを追加します
* プロビジョニングコレクションでの VM シリーズ / サイズの割り当てのサポート
* ライセンスサーバー設定が不適切に適用されたシナリオのサブセットのバグ修正
* バグ修正–展開後に意図したとおりに一時フォルダを削除します
* Azure ですでに使用されている VM と同じ IP アドレスを持つサーバを作成する場合のバグ修正




=== Azure コスト試算ツール

* AVD のお客様が Windows OS VM ではなく Linux OS VM を購入したことを反映して価格を更新します
* 関連する Microsoft ライセンスを含めるオプションを追加しました
* Microsoft の更新された計算機に従って使用されるストレージのデフォルトに更新します（フラットまたはユーザ数）
* SQL に関して D4s v3 VM の料金を追加
* VM の編集時に表示問題のバグ修正




== CWMS 5.3 リリース： Thurs. 、 2019 年 10 月 3 日

_ コンポーネント： _5.3 Cloud Workspace Management Suite_When ： _ Thursday October 3 、 2019 年 10 月 3 日午後 10 時 ~ 午後 11 時 Eastern _Impact ： _ エンドユーザ向けのクラウドワークスペースデスクトップおよびアプリケーションサービスへのアクセスは中断されません。Cloud Workspace Management Suite へのアクセスは引き続き可能です。



=== Cloud Workspace Management Suite の略

* [ 戻る ] をクリックすると、 [ 組織 ] タブではなく [ ワークスペース ] タブに戻ります
* CWMS を使用して Azure でクラウドワークスペースをプロビジョニングする場合は、検証ステップで AADDS が正常に検証されていることを確認します
* 最大 256 文字のユーザ名をサポートします




=== CWA 設定

* ユーザが自分のアカウントを CWMS にリンクしていても、初めて導入のプロビジョニングを完了していない場合に、リンクされたパートナーアカウントを覚えておくためのシステムの改善点
* CSP ワークフロー中にクラウドワークスペース展開をプロビジョニングするテナントを選択したときに表示される javascript エラーのバグ修正




=== Azure コスト試算ツール

* Azure Cost Estimator で Microsoft のライセンスを表示するかどうかを選択するオプションを追加します
* この機能を有効にしないと ( デフォルトの動作 ) 、組織が EA または既存の Microsoft Office 365 ライセンスを介してすでに Microsoft ライセンスを所有していることを前提としています
* これを有効にすると、解決策をより包括的に TCO レベルで理解できます
* ユーザが 15 分単位でアップタイムを切り替えていたときに、アップタイムがわずかにオフになったバグ修正
* ユーザが午後 / 夕方（ PM 設定）に開始するように設定し、朝（ AM 設定）に終了するシナリオのバグ修正




== CWMS 5.3 リリース： Thurs. 、 2019 年 9 月 19 日

_ コンポーネント： _5.3 Cloud Workspace Management Suite_When ： _ Thursday September 19 （ 2019 年 9 月 19 日午後 10 時 ~ 午後 11 時）： _ エンドユーザー向けのクラウドワークスペースデスクトップおよびアプリケーションサービスへのアクセスは中断されません。Cloud Workspace Management Suite へのアクセスは引き続き可能です。



=== Cloud Workspace Management Suite の略

* デフォルトでは、 Azure 導入のリソース割り当てタイプは [Fixed] に設定されています。選択されている VM シリーズ / サイズは、 CWMS の管理者によって定義された VM です
* ユーザアクティビティ監査機能の検索機能を追加します
* ユーザーの一括作成プロセスの改善–ユーザーをインポートするときに、 ［ 次回ログオン時にパスワード変更を強制する ］ 機能を有効にします
* バグ修正により、 55 分ではなく 5 分後にセッションの非アクティブ時のタイムアウトに関する警告が誤って表示される
* ユーザーサポートロールの修正–このロールを持つ管理者のサブセットが、組織のユーザーのリストを表示できませんでした
* ユーザによるソート修正–ユーザ名でソートすると、ステータスでソートするのではなく、目的の操作を行うことができます
* [Deployments] タブの [Overview] セクションに、ハートビート機能が追加されました。これは、展開が最後にポーリングされてオンラインかどうかを確認するときに表示されます
* ワークフローの改善 - AVD モジュールで [ 戻る ] をクリックすると、組織モジュールではなくワークスペースモジュールが使用されます
* マスタークライアントレポートが存在することを確認します。非マスターソフトウェアパートナーの該当しない SPLA レポートは非表示にしてください




=== クラウドワークスペースツールとサービス

* AVD でサポートされている ThinPrint エージェントではないため、ホストプール内の Azure Virtual Desktop （ AVD ）サーバから標準の ThinPrint エージェントを削除します。その代わり、企業は「リストアに関する解決策」について ThinPrint に問い合わせる必要があります。
* 強化されたパスワード暗号化機能
* CWMGR1 の管理者がパスワードの有効期限を Null に設定した場合、パスワード強制通知（ PEN ）のバグ修正。「次回ログオン時にパスワードを変更」機能を使用しても、意図したとおりに動作しませんでした




=== Cloud Workspace for Azure セットアップアプリ

* 国際的な管理者向けの修正–国が米国でない場合は、これを長くすると州が必要になります。
* Partner Admin Link （ PAL ）経由で CloudJumper を適用すると、 Azure のサブスクリプションレベルでの提供と今後の導入が可能になります




== CWMS 5.3 リリース： Thurs. 、 2019 年 9 月 5 日

_ コンポーネント： _5.3 Cloud Workspace Management Suite_ 日付： _ 木曜日 2019 年 9 月 5 日午後 10 時 ~ 午後 11 時（ Eastern _Impact ）： _ エンドユーザー向けのクラウドワークスペースデスクトップおよびアプリケーションサービスへのアクセスは中断されません。Cloud Workspace Management Suite へのアクセスは引き続き可能です。



=== Cloud Workspace Management Suite の略

* User Support Only ロールの更新：
* 検索 / フィルタリングユーザー機能を追加します
* ユーザーとその接続に接続ステータス列を含める
* 次回ログイン時にパスワード変更を強制する機能へのアクセスを提供します
* クライアント削除機能の表示を削除します
* 1 時間非アクティブの後に CWMS のログアウトを強制します
* リソース割り当てタイプが固定に設定されている VM ロールを表示するときに、 VM シリーズ / サイズが正しく表示されないという表示問題の修正
* Display 問題では、ワークロードのスケジューリングが [ 常にオフ ] に設定されている環境では、 CWMS で不適切な設定が表示されていましたが、正しくは [ 常にオフ ] に設定されています
* アクセス権の更新– CWMS 管理者が CWMS の Resources 関数にアクセスできない場合は、 [ リソーススケジュール ] タブを削除します
* VDI ユーザホストプールに複数の VM インスタンスを追加できないようにします
* AVD ホストプール内のセッションホストあたりの最大ユーザー数の修正を表示–これらの値は、 [ ワークロードのスケジュール ] タブの [ ライブスケーリング ] セクションで設定された値と一致します




=== クラウドリソースアプリケーション

* 機能の更新–コマンドラインの使用方法のサポート




=== クラウドワークスペースツールとサービス

* vCloud REST インターフェイスのサポート




== CWMS 5.3 リリース： 2019 年 8 月 22 日

_ コンポーネント： _5.3 Cloud Workspace Management Suite_When ： _ Thursday August 22 、 2019 年 10 時 ～ 23 時 Eastern _Impact ： _ エンドユーザ向けのクラウドワークスペースデスクトップおよびアプリケーションサービスへのアクセスは中断されません。Cloud Workspace Management Suite へのアクセスは引き続き可能です。



=== 5.3 Cloud Workspace Management Suite の略

* AVD がサポートされる状況を定義する [AVD] タブにメッセージを追加します
* AVD タブからワークスペースに戻るときのワークフローが改善されました
* AVD モジュールの説明のテキスト編集




=== 5.3 Cloud Workspace for Azure のセットアップ

* お客様の登録が米国外の場合は、州への入国要件を削除します
* 現在、 CWMGR1 を D シリーズ VM として展開し、初期展開後のコスト目的で B2ms にサイズ変更します




=== クラウドワークスペースツールとサービス

* レガシー（ 2008 R2 ）環境での SSL 証明書管理に関するバグ修正
* 証明書の適用とライフサイクル管理に関するその他の健全性チェック




== CWMS 5.3 リリース： 2019 年 8 月 8 日

_ コンポーネント： _5.3 Cloud Workspace Management Suite_When ： _ Thursday August 8 、 2019 年 10 時 ～ 23 時 Eastern _Impact ： _ エンドユーザ向けのクラウドワークスペースデスクトップおよびアプリケーションサービスへのアクセスは中断されません。Cloud Workspace Management Suite へのアクセスは引き続き可能です。



=== 5.3 Cloud Workspace Management Suite の略

* CWMS から CWMGR1 に接続するシナリオのサブセットに関するバグ修正が期待どおりに機能していません

