---
sidebar: sidebar 
permalink: Management.Deployments.logical_hierarchy_overview.html 
summary: スクリプトの文書作成 - AMD Radeon Instinct ドライバ 
keywords:  
---
= VDS 論理階層の概要
:allow-uri-read: 




== 概要

VDS では、概念が論理階層のさまざまなレイヤに整理されます。この記事では、それらがどのように連携するかについて概説します。



=== VDS 組織スキーム

VDS 管理ポータルは、にあります https://manage.vds.netapp.com[]。この Web インターフェイスでは、 VDS 関連のすべてのオブジェクトを 1 つの画面で管理できます。VDS Web UI には、コンポーネントと論理コンテナの次の階層があります。



==== VDS の導入

_Deployment_ は '_VDS ワークスペース _ を含む 'VDS の概念です特定の導入アーキテクチャでは、複数の VDS ワークスペースを配置できます。


NOTE: 1 つの導入環境で複数の VDS ワークスペースを実行することは「マルチテナンシー」と呼ばれ、 RDS 導入ではオプションとしてのみ機能します。 AVD の導入では、このアプローチはサポートされません。

展開は Active Directory ドメインによって定義され、 AD ドメインと展開の間に 1:1 の関係があります。

導入環境内のすべての VDS ワークスペースで共有される導入をサポートするために導入される特定の VM リソースがあります。例：各導入には、 VDS アプリケーションを実行するサーバである CWMGR1 という名前の VM が含まれています。これは SQL Express データベースであり、展開内の VDS ワークスペース（および含まれるリソース）の管理を容易にします。



==== VDS ワークスペース


WARNING: 「 * VDS * Workspace 」と「 * AVD * Workspace 」には違いがあります。

VDS ワークスペースは、クライアント ( エンドユーザー ) リソースの配置内の論理コンテナです。これらのリソースには、仮想マシン（セッションホスト、アプリケーションサーバ、データベースサーバ、ファイルサーバなど）、仮想ネットワーク、 ストレージやその他のハイパーバイザーインフラ：

VDS ワークスペースには、ユーザー、セキュリティグループ、ワークロードスケジューリング、アプリケーション、自動化、 VM 、および AVD の構成。

通常 'VDS ワークスペースは単一の会社 ' つまり ( エンタープライズ環境の場合 ) ビジネスユニットと連携します



==== VDS サイト

導入環境内では、複数のサイトを作成して異なるインフラプロバイダを表すことができ、すべてを 1 つの導入環境で管理できます。

これは、単一の企業またはビジネスユニットが、複数の物理的な場所（北米や EMEA など）、ハイパーバイザーサブスクリプション（コストをビジネスユニットに合わせるため）、ハイパーバイザー（ Azure のユーザ、 Google Compute 、 vSphere のオンプレミス HCI など）でユーザやアプリケーションをホストする必要がある場合に役立ちます。



==== AVD ワークスペース


WARNING: 「 * VDS * Workspace 」と「 * AVD * Workspace 」には違いがあります。

AVD ワークスペースは 'VDS ワークスペースと VDS サイト内にある論理コンテナです同じ導入環境で管理ポリシーと運用ポリシーをセグメント化するために VDS サイトと同じように使用できます。



==== AVD ホストプール

AVD ホストプールは、 AVD ワークスペース内に配置され、セッションホストとアプリケーショングループのユーザーを保持して、ユーザーセッションをサーバー化し、個々のリソースへのアクセスを制御する論理コンテナです。



==== AVD アプリケーショングループ

各 AVD ホストプールは、 1 つの「デスクトップ」アプリケーショングループから始まります。この（または他の）アプリグループにユーザーやグループを割り当てて、割り当てられたユーザーにアプリグループ内のリソースへのアクセスを許可することができます。

VDS のホストプール内に追加のアプリケーショングループを作成できます。追加のアプリケーショングループはすべて、 Windows デスクトップの完全なエクスペリエンスではなく、 RemoteApp のリソースを提供し、 RemoteApp のリソースを提供します。
