---
sidebar: sidebar 
permalink: Management.User_Administration.multi-factor_authentication.html 
summary: 多要素認証（ MFA ）の設定 
keywords:  
---
= 多要素認証（ MFA ）
:allow-uri-read: 




== 概要

NetApp Virtual Desktop Service （ VDS ）には、 SMS / E メールベースの MFA サービスが追加料金なしで含まれています。このサービスは、他のサービス（例 Azure Conditional Access （ Azure 条件付きアクセス）の略）。 VDS への管理者ログインおよび仮想デスクトップへのユーザログインを保護するために使用できます。



== MFA の基礎

* 管理ユーザ、個々のエンドユーザ、またはすべてのエンドユーザに VDS MFA を割り当てることができます
* VDS MFA では、 SMS または E メール通知を送信できます
* VDS MFA には、セルフサービスの初期セットアップとリセット機能があります




== ガイドの範囲

このガイドでは、 MFA の設定方法とエンドユーザエクスペリエンスの図を示します

.このガイドでは、次の内容について説明します。
. <<Enabling MFA for Individual Users,個々のユーザに対する MFA の有効化>>
. <<Requiring MFA for All Users,すべてのユーザに MFA を要求>>
. <<Enabling MFA for Individual Administrators ,個々の管理者に対する MFA の有効化>>
. <<End User Initial Setup,エンドユーザの初期セットアップ>>




== 個々のユーザに対する MFA の有効化

ユーザー詳細ページの個々のユーザーに対して MFA を有効にするには、 _Multi-factor Auth Enabled_ をクリックします

[ ワークスペース ]>[ ワークスペース名 ]>[ ユーザーとグループ ]>[ ユーザー名 ]>[ 多要素認証有効 ]>[ 更新 ] の順に選択します

MFA は、すべてのユーザに割り当てることもできます。この設定が適用されている場合は、チェックボックスがオンになり、 _ （クライアント設定経由） _ がチェックボックスラベルに追加されます。



== すべてのユーザに MFA を要求

ワークスペース詳細ページのすべてのユーザーに対して MFA を有効にして適用するには ' すべてのユーザーに対して enable_MFA をクリックします

[ ワークスペース ]>[ ワークスペース名 ]>[ 有効なすべてのユーザーの MFA ]>[ 更新 ] を選択します



== 個々の管理者に対する MFA の有効化

VDS ポータルにアクセスする管理者アカウントでも MFA を使用できます。これは、管理者ごとに管理詳細ページで有効にできます。[ 管理者 ] > [ 管理者名 ] > [ 多要素認証が必要 ] > [ 更新 ] を選択します



== 初期セットアップ

MFA を有効にしたあとの最初のログインでは、ユーザまたは管理者が E メールアドレスまたは携帯電話番号の入力を求められます。登録が正常に完了したことを確認する確認コードが表示されます。
