= 概要




== 概要

データの移行は、あらゆる種類のクラウド解決策への移行でほぼユニバーサルな要件となります。管理者は仮想デスクトップにデータを移行する責任がありますが、ネットアップの経験は豊富なお客様への移行に役立つことが証明されています。仮想デスクトップ環境は単にホストされた Windows 環境であるため、必要な方法はすべてサポートされている可能性があります。

.通常移行されるデータ：
* ユーザープロファイル（デスクトップ、ドキュメント、お気に入りなど）
* File Server Shares （ファイルサーバ共有）
* データ共有（アプリケーションデータ、データベース、バックアップキャッシュ）


.仮想デスクトップ環境では、データを保存して整理する 2 つの主要な場所があります。
* ユーザー（通常は H ： \ ）ドライブ：これは、各ユーザーに表示されるマッピングされたドライブです。
+
** これは <drive> ： \home\CustomerCode\user.name \path にマッピングされています
** 各ユーザーにはそれぞれ H:\ ドライブがあり、別のユーザーを表示できません


* 共有（通常は I ： \ ）ドライブ：これは、すべてのユーザーが認識できる共有マッピングされたドライブです
+
** これは <drive> ： \data\CustomerCode\path にマッピングされています
** すべてのユーザーがこのドライブにアクセスできます。含まれているフォルダ / ファイルへのアクセス権のレベルは 'VDS のフォルダセクションで管理されます






== 一般的な移行プロセス

. クラウド環境へのデータのレプリケート
. H ： \ ドライブと I ： \ ドライブの適切なパスにデータを移動します
. 仮想デスクトップ環境で適切な権限を割り当てます




== FTPS 転送と考慮事項



=== FTPS での移行

. CWA の導入プロセス中に FTPS サーバーの役割が有効になっていた場合は 'VDS にログインしてレポートに移動し ' 組織のマスタークライアントレポートを実行して 'FTPS 資格情報を収集します
. データをアップロードします
. H ： \ ドライブと I ： \ ドライブの適切なパスにデータを移動します
. フォルダモジュールを使用して、仮想デスクトップ環境で適切な権限を割り当てます



NOTE: FTPS 経由でデータを転送する場合、中断を行うとデータが意図したとおりに転送されなくなります。Virtual Desktop Services が管理するサーバは夜間に再起動されるため、標準の夜間転送方式が中断される可能性があります。これを回避するには、管理者が移行モードを有効にして VM が 1 週間リブートされないようにします。

移行モードの有効化は簡単です。組織に移動し、 [ 仮想デスクトップの設定 ] セクションまでスクロールダウンして、 [ 移行モード ] のチェックボックスをオンにし、 [ 更新 ] をクリックします。


NOTE: 導入先のゲートウェイを強化することで、 PCI 、 HIPAA 、 NIST の制御に対応できるようにするコンプライアンス設定を管理者が有効にすることを推奨します。これにより、デフォルトの FTP サーバのロール（有効な場合）が、ポート 21 を介したデフォルトの暗号化されていない送信を受け入れることができなくなります。Filezilla では SFTP を使用できないため、ポート 990 経由で FTPS を使用して接続を行う必要があります。

この設定を有効にするには、 CWMGR1 に接続して CwVmAutomationService プログラムに移動し、 PCI v3 準拠を有効にします。



== 同期ツールと考慮事項

エンタープライズファイルの同期と共有は、 EFSS や同期ツールと呼ばれることが多いため、データの移行に非常に役立ちます。このツールでは、カットオーバーまでの各側の変更がキャプチャされるからです。Office 365 に付属している OneDrive などのツールを使用すると、ファイルサーバーのデータを同期できます。また、共有データを共有に一度展開できる場合にユーザーが VDI サーバーに共有コンテンツを同期しようとしない限り（通常は i:\ ）、ユーザーと VM の間に 1:1 の関係が存在する VDI ユーザーの展開にも役立ちます。 組織全体で使用できるようにします。SQL と類似データの移行（開いているファイル）

.一般的な同期ソリューションや移行ソリューションでは、開いているファイルは転送されません。これには、次のようなファイルタイプが含まれます。
* メールボックス (.ost) ファイル
* QuickBooks ファイル
* Microsoft Access ファイル
* SQL データベース


つまり、ファイル全体の 1 つの要素（たとえば、 1 つの新しい電子メールが表示されます）またはデータベース（ 1 つの新しいレコードがアプリケーションのシステムに入力された場合）は、ファイル全体が異なり、標準の同期ツール（ Dropbox など）になります。 完全に新しいファイルであると考え、再度移動する必要があります。必要に応じて、サードパーティプロバイダから購入できる専用のツールが用意されています。

これらの移行を処理するもう 1 つの一般的な方法は、サードパーティの VAR へのアクセスを提供することです。 VAR は、データベースのインポート / エクスポートを合理化しています。



== 出荷されているドライブ

多くのデータセンタープロバイダは、もはやハードドライブを出荷していません。つまり、お客様固有のポリシーや手順に従う必要があります。

Microsoft Azure では、組織が Azure Data Box を使用できるようにしています。管理者は Microsoft 担当者と調整することで、この Box を活用できます。
