= 概要




== 概要

VDS には、アプリケーションの自動化と使用権に関する強力な機能が組み込まれています。この機能を使用すると、ユーザーは同じセッションホストに接続している間に、異なるアプリケーションにアクセスできます。これは、ショートカットを非表示にするカスタム GPO と、ユーザーのデスクトップにショートカットを選択的に配置する自動化によって実現されます。


NOTE: このワークフローは、環境 RDS 配置のみを対象としています。AVD アプリケーションの使用権に関するドキュメントについては ' を参照してください link:Management.Applications.AVD_application_entitlement_workflow.html["AVD のアプリケーションエンタイトルメントワークフロー"]

アプリケーションは 'VDS で管理されるセキュリティグループを介して ' ユーザーに直接割り当てることもできます

.アプリケーションのプロビジョニングプロセスは、以下の手順で構成されます。
. アプリカタログにアプリを追加します
. ワークスペースにアプリを追加します
. すべてのセッションホストにアプリケーションをインストールします
. ショートカットパスを選択します
. ユーザーやグループにアプリを割り当てます



NOTE: ステップ 3 と 4 は、次に示すようにスクリプトイベントで完全に自動化できます

.ビデオチュートリアル
video::19NpO8v15BE[youtube, ]


== アプリケーションカタログにアプリケーションを追加します

VDS アプリケーションエンタイトルメントは、 App Catalog から始まります。これは、エンドユーザー環境への展開に使用できるすべてのアプリケーションのリストです。

.カタログにアプリケーションを追加するには、次の手順を実行します
. VDS にログインします https://manage.cloudworkspace.com[] プライマリ管理者のクレデンシャルを使用する。
. 右上の矢印アイコンをクリックして、 [ ユーザー名 ] の横にある [ 設定 ] を選択します。
. [ アプリケーションカタログ（ App Catalog ） ] タブをクリックする。
. [ アプリケーションカタログ ] タイトルバーの [ アプリケーションの追加 ] オプションをクリックします。
. アプリケーションのグループを追加するには、 [ アプリケーションのインポート ] オプションを選択します。
+
.. ダウンロードする Excel テンプレートを提供するダイアログが表示され、アプリケーションリストに適した形式が作成されます。
.. この評価では、ネットアップ VDS はインポート用のサンプルアプリケーションリストを作成しました。このリストは、こちらから参照できます。
.. [ アップロード ] 領域をクリックし、アプリケーションテンプレートファイルを選択して、 [ インポート ] ボタンをクリックします。


. 個々のアプリケーションを追加するには、「アプリケーションを追加」ボタンを選択すると、ダイアログボックスが表示されます。
+
.. アプリケーションの名前を入力します。
.. 外部 ID を使用して、製品 SKU や請求トラッキングコードなどの内部トラッキング ID を入力できます（オプション）。
.. アプリケーションをサブスクリプション製品としてレポートする場合は、 [ サブスクリプション ] チェックボックスをオンにします（オプション）。
.. 製品がバージョン（ Chrome など）ごとにインストールされない場合は、 [ バージョンが不要 ] チェックボックスをオンにします。これにより、バージョンを追跡することなく、「継続的な更新」製品をインストールできます。
.. 逆に、製品が複数の名前付きバージョン（ QuickBooks など）をサポートしている場合は、このチェックボックスをオンにして、複数のバージョンをインストールし、使用可能な各バージョンをエンドユーザが使用できるアプリケーションのリストに記載して VDS を設定する必要があります。
.. VDS でこの製品のデスクトップアイコンをプロビジョニングしない場合は、 [ ユーザーデスクトップなし ] アイコンをオンにします。これは、エンドユーザがアクセスするアプリケーションを持っていないため、 SQL Server などのバックエンド製品に使用されます。
.. 「アプリを関連付ける必要があります」とは、関連付けられたアプリをインストールする必要性を強制するものです。たとえば、クライアントサーバーアプリケーションでは、 SQL Server または MySQL もインストールする必要があります。
.. License Required （ライセンスが必要）ボックスをオンにすると 'VDS はアプリケーションのステータスを Active に設定する前に ' このアプリケーションのインストール用にライセンスファイルをアップロードするよう要求しますこの手順は 'VDS のアプリケーション詳細ページで実行します
.. すべてに表示–アプリケーションエンタイトルメントは、マルチチャネル階層内の特定のサブパートナーに限定できます。評価目的では、チェックボックスをクリックして、すべてのユーザーが使用可能なアプリケーションリストでそのアプリケーションを表示できるようにします。






== アプリケーションをワークスペースに追加します

展開プロセスを開始するには、アプリケーションをワークスペースに追加します。

.これを行うには、次の手順を実行します。
. ワークスペースをクリックします
. [ アプリ ] までスクロールダウンします
. 追加をクリックします
. アプリケーションのチェックボックスをオンにし、必要な情報を入力して、アプリケーションの追加をクリックし、アプリの追加をクリックします。




== アプリケーションを手動でインストールします

アプリケーションがワークスペースに追加されたら、そのアプリケーションをすべてのセッションホストにインストールする必要があります。これは手動で行うことも、自動化することもできます。

.セッションホストにアプリケーションを手動でインストールするには、次の手順を実行します
. サービスボードに移動します。
. サービスボードタスクをクリックします。
. サーバー名をクリックして、ローカル管理者として接続します。
. アプリをインストールし、このアプリへのショートカットが [ スタート ] メニューパスにあることを確認します。
+
.. Server 2016 および Windows 10 ： C ： \ProgramData\Microsoft\Windows\Start Menu\Programs 。


. サービスボードタスクに戻り、 [ 参照 ] をクリックして、ショートカットまたはショートカットを含むフォルダを選択します。
. 選択した方が、アプリケーションの割り当て時にエンドユーザーデスクトップに表示されるものです。
. フォルダは、アプリケーションが実際に複数のアプリケーションである場合に便利です。たとえば、「 Microsoft Office 」はフォルダとして簡単に展開でき、各アプリケーションはフォルダ内のショートカットとして使用できます。
. [ インストールの完了 ] をクリックします
. 必要に応じて、 [ 作成済み ] アイコン [ サービスボードタスクの追加 ] を開き、アイコンが追加されていることを確認します。




== ユーザにアプリケーションを割り当てます

アプリケーションの使用権は VDS によって処理され、アプリケーションは 3 つの方法でユーザに割り当てることができます

.ユーザにアプリケーションを割り当てます
. User Detail ページに移動します。
. 「アプリケーション」セクションに移動します。
. このユーザが必要とするすべてのアプリケーションの横にあるチェックボックスをオンにします。


.アプリケーションにユーザを割り当てます
. [ ワークスペースの詳細 ] ページの [ アプリケーション ] セクションに移動します。
. アプリケーションの名前をクリックします。
. アプリケーションのユーザの横にあるチェックボックスをオンにします。


.アプリケーションとユーザをユーザグループに割り当てます
. [ ユーザーとグループの詳細 ] に移動します。
. 新しいグループを追加するか、既存のグループを編集します。
. グループにユーザとアプリケーションを割り当てます。

