= CWMS 5.2 リリース： 2019 年 12 月 2 日、月



NOTE: 今後の CWMS v5.2 については、リリースはすべて修正プログラムと見なされます。



== CWMS 5.2 リリース： 2019 年 12 月 2 日、月

コンポーネント： 5.2 Cloud Workspace Management Suite 、 2019 年 12 月 2 日（月）午後 10 時 ~ 午後 11 時（東部標準時）：エンドユーザ向けの Cloud Workspace デスクトップとアプリケーションサービスへのアクセスが中断されないままになります。Cloud Workspace Management Suite へのアクセスは引き続き可能です。

このリリースサイクルの更新はありません。



== CWMS 5.2 リリース： Thurs. 、 2019 年 11 月 14 日

コンポーネント： 5.2 Cloud Workspace Management Suite 、 2019 年 11 月 14 日（木）午後 10 時 ~ 午後 11 時の東部への影響：エンドユーザ向けのクラウドワークスペースデスクトップおよびアプリケーションサービスへのアクセスが中断されないままとなります。Cloud Workspace Management Suite へのアクセスは引き続き可能です。

このリリースサイクルの更新はありません。



== CWMS 5.2 リリース： Thurs. 、 2019 年 10 月 31 日

コンポーネント： 5.2 Cloud Workspace Management Suite 、 2019 年 10 月 31 日（木）午後 10 時 ~ 午後 11 時の東部への影響：エンドユーザ向けのクラウドワークスペースデスクトップおよびアプリケーションサービスへのアクセスが中断されないままになります。Cloud Workspace Management Suite へのアクセスは引き続き可能です。

このリリースサイクルの更新はありません。



== CWMS 5.2 リリース： Thurs. 、 2019 年 10 月 17 日

コンポーネント： 5.2 Cloud Workspace Management Suite 、 2019 年 10 月 17 日（木）午後 10 時 ~ 午後 11 時の東部への影響：エンドユーザ向けのクラウドワークスペースデスクトップおよびアプリケーションサービスへのアクセスが中断されないままとなります。Cloud Workspace Management Suite へのアクセスは引き続き可能です。

このリリースサイクルの更新はありません。



== CWMS 5.2 リリース： Thurs. 、 2019 年 10 月 3 日

コンポーネント： 5.2 Cloud Workspace Management Suite 、 2019 年 10 月 3 日（木）午後 10 時 ~ 午後 11 時の東部への影響：エンドユーザ向けのクラウドワークスペースデスクトップおよびアプリケーションサービスへのアクセスが中断されないままとなります。Cloud Workspace Management Suite へのアクセスは引き続き可能です。

このリリースサイクルの更新はありません。



== CWMS 5.2 リリース： Thurs. 、 2019 年 9 月 19 日

コンポーネント： 5.2 Cloud Workspace Management Suite 、 2019 年 9 月 19 日（木）午後 10 時 ~ 午後 11 時の東部への影響：エンドユーザ向けのクラウドワークスペースデスクトップおよびアプリケーションサービスへのアクセスが中断されないままとなります。Cloud Workspace Management Suite へのアクセスは引き続き可能です。



=== Cloud Workspace Management Suite の略

Azure 展開のリソース割り当てタイプを既定値として [ 固定 ] に設定します。 選択された VM シリーズ / サイズが、 CWMS の管理者によって定義された VM であるユーザアクティビティ監査機能のバグ修正セッション非アクティブタイムアウト警告を誤って表示する問題 5 分後にユーザサポートロール修正–このロールを持つ管理者のサブセット 組織のユーザーのリストを表示できませんでしたユーザーのソート修正–ユーザー名でソートすると、ステータスでソートする代わりに意図したとおりに機能します。マスタークライアントレポートが存在することを確認します。非マスターソフトウェアパートナーの該当する SPLA レポートを非表示にします



=== Cloud Workspace のツールとサービス

パスワード失効日が CWMGR1 の管理者によって null に設定されている場合、パスワード強制通知（ PEN ）のための強化されたパスワード暗号化機能を使用すると、意図したとおりに「次回ログオン時のパスワード変更」機能を使用できませんでした



=== Cloud Workspace for Azure セットアップアプリケーション

国際的な管理者向けの修正–国が米国でない場合は、これを長くすると州が必要になります。Partner Admin Link （ PAL ）経由で CloudJumper を適用すると、 Azure のサブスクリプションレベルでの提供と今後の導入が可能になります



== CWMS 5.2 リリース： Thurs. 、 2019 年 9 月 5 日

コンポーネント： 5.2 Cloud Workspace Management Suite 、 2019 年 9 月 5 日（木）午後 10 時 ~ 午後 11 時の東部への影響：エンドユーザ向けのクラウドワークスペースデスクトップおよびアプリケーションサービスへのアクセスが中断されないままとなります。Cloud Workspace Management Suite へのアクセスは引き続き可能です。



=== Cloud Workspace Management Suite の略

User Support Only ロールの更新： * 検索の追加 / ユーザーのフィルタリング機能 * ユーザーとその接続の [ 接続ステータス ] 列を含む * 次のログイン時にパスワードを強制変更する機能へのアクセスを提供 * [ クライアントの削除 ] 機能の表示を削除 1 時間非アクティブの後に CWMS のログアウトを強制するディスプレイ問題の修正 リソース割り当てタイプが固定に設定されている VM ロールを表示するときに、 VM シリーズ / サイズが正しく表示されないという問題が表示される問題では、ワークロードのスケジュールが常にオフに設定されている環境の CWMS で不適切な設定が表示されていました。 [ 権限の更新 ] のシーンの背後で [ 常にオフ ] に正しく設定されているにもかかわらず、 CWMS 管理者が CWMS の [ リソース ] 機能にアクセスできない場合は、 [ リソースのスケジュール ] タブを削除します



=== クラウドリソースアプリケーション

機能の更新–コマンドラインの使用方法のサポート



=== Cloud Workspace のツールとサービス

vCloud REST インターフェイスのサポート



== CWMS 5.2 リリース： Thurs. 、 2019 年 8 月 22 日

コンポーネント： 5.2 Cloud Workspace Management Suite 、 2019 年 8 月 22 日（木）午後 10 時 ~ 午後 11 時の東部への影響：エンドユーザ向けのクラウドワークスペースデスクトップおよびアプリケーションサービスへのアクセスが中断されないままとなります。Cloud Workspace Management Suite へのアクセスは引き続き可能です。



=== Cloud Workspace Management Suite の略

一部のモニターサイズのユーザープロファイルでディスプレイ問題を修正する動的でないアプリケーションサービスについて明確にするメッセージを追加します。変更が有効になるまでに数分かかる場合があることを管理者に通知します。動的でないアプリケーションサービスの場合は、 [ 再更新 ] ボタンを追加して、新しいクライアント / ユーザーが持っているかどうかを簡単に確認します が追加されました



=== Cloud Workspace for Azure のセットアップ

既存の CWMS アカウントへのリンクを確立する際の登録プロセスの MFA のサポートを追加プロビジョニング後の手順へのリンク–新しい公開 KB の改善へのリンクとプロビジョニング後の手順へのリンク–リンクが新しいタブに表示されます



=== Cloud Workspace のツールとサービス

レガシー（ 2008 R2 ）環境での SSL 証明書管理に関するバグ修正証明書の適用とライフサイクル管理に関する追加の健全性チェック



== CWMS 5.2 リリース： Thurs. 、 2019 年 8 月 8 日

コンポーネント： 5.2 Cloud Workspace Management Suite 、 2019 年 8 月 8 日（木）午後 10 時 ~ 午後 11 時の東部への影響：エンドユーザ向けの Cloud Workspace デスクトップとアプリケーションサービスへのアクセスが中断されないままになります。Cloud Workspace Management Suite へのアクセスは引き続き可能です。

このリリースの更新はありません。



== CWMS 5.2 リリース： Thurs. 、 2019 年 7 月 25 日

コンポーネント： 5.2 Cloud Workspace Management Suite 、 2019 年 7 月 25 日（木）午後 10 時から 23 時（東部標準時）：エンドユーザ向けの Cloud Workspace デスクトップとアプリケーションサービスへのアクセスが中断されないままになります。Cloud Workspace Management Suite へのアクセスは引き続き可能です。



=== 5.2 CWA のセットアップ

CWA セットアップユーザーを CloudJumper Public KB に誘導するメッセージをプロビジョニング後に表示します。ここでは次の手順を確認し、登録プロセス時に米国外の国の処理を改善する方法を確認できます。また、新しく作成した CWMS のパスワードを確認するフィールドを追加しました RDS ライセンスが不要な場合は、 CWA 設定プロセス中にログインして SPLA ライセンスを削除します



=== 5.2 Cloud Workspace Management Suite の略

単一サーバー展開での CWMS 管理者に対する HTML5 接続処理の改善ユーザーの処理を再開するシナリオのバグ修正（以前に失敗した場合） RDS ライセンスが不要な状況では、「 Internal Server Error 」というメッセージが表示され、 CWMS 内の自動 SSL 証明書処理や自動 SMTP などの SPLA ライセンスの削除セクションが表示されました



=== 5.2 Cloud Workspace のツールとサービス

VDI ユーザが電源オフに設定されているときに VM からログアウトすると、その VM の Azure Backup 拡張機能の電源がオフになります。 TSD1 サーバを VM としてリストアする場合は、 TS VM としてリストアする。追加の TSD VM を用意する代わりに、バックエンド処理速度とセキュリティを向上させる Azure バックアップ用の Azure VM を用意する



=== 5.2 REST API

サーバ情報の処理が改善され、 Wake-on-Demand サーバのロード時間が短縮されました



== CWMS 5.2 リリース： Thurs. 、 2019 年 7 月 11 日

コンポーネント： 5.2 Cloud Workspace Management Suite 、 2019 年 7 月 11 日（木）午後 10 時 ~ 午後 11 時の東部への影響：エンドユーザ向けの Cloud Workspace デスクトップとアプリケーションサービスへのアクセスが中断されないままになります。Cloud Workspace Management Suite へのアクセスは引き続き可能です。



=== 5.2 Cloud Workspace のツールとサービス

バックグラウンドで継続的にセキュリティを強化自動生成証明書の継続的な安定性の強化最小特権方法論の改善–権限の少ないアカウントを使用するように調整し、一般的なロックダウンの影響を受けないように調整して、 Azure 展開用の統合バックアップのための夜間リブートの改善 GCP 展開バグ修正のための統合バックアップの改善を実行します 必要に応じて、手動で証明書を管理できるようにするために、すでにプロセス強化が修正されている場合に、リソース調整を適用するためにサーバを再起動する必要はなくなりました



== CWMS 5.2 リリース： Thurs. 、 2019 年 6 月 20 日

コンポーネント： 5.2 Cloud Workspace Management Suite 、 2019 年 6 月 20 日（木）午後 10 時 ~ 午後 11 時の東部への影響：エンドユーザ向けの Cloud Workspace デスクトップとアプリケーションサービスへのアクセスが中断されないままになります。Cloud Workspace Management Suite へのアクセスは引き続き可能です。



=== 5.2 Cloud Workspace Management Suite の略

CRA プロセス経由で CWMS にインポートされたユーザの処理が改善されました。 CWMS Web インターフェイスの下部で年更新されたシナリオのサブセットについては、ワークスペースモジュールの「サーバ」セクションに正しいストレージが表示されます



=== 5.2 Cloud Workspace のツールとサービス

証明書の自動化機能の強化



=== 5.2 REST API

表示の修正–ライブスケーリング機能を再度開いたときに、ライブスケーリング機能で以前に入力した正しい値を表示します。これにより、パワーユーザーの役割（ VDI ユーザー）のデフォルトのバックアップスケジュールを作成できます。



== CWMS 5.2 リリース： Thurs. 、 2019 年 6 月 6 日

コンポーネント： 5.2 Cloud Workspace Management Suite 、 2019 年 6 月 6 日（木）午後 10 時 ~ 午後 11 時の東部への影響：エンドユーザ向けの Cloud Workspace デスクトップとアプリケーションサービスへのアクセスが中断されないままになります。Cloud Workspace Management Suite へのアクセスは引き続き可能です。



=== 5.2 Cloud Workspace のツールとサービス

プラットフォーム通知用の複数の E メールの処理の改善ワークロードのスケジューリングがサーバをオフにしないシナリオのサブセットのバグ修正 Azure Backup からサーバをリストアしないシナリオのサブセットのためのバグ修正適切なストレージタイプとをリストアしませんでしたデフォルトのストレージタイプ



=== 5.2 CWA のセットアップ

CWA セットアッププロセス中のセキュリティ強化の継続サブネットとゲートウェイ設定の自動処理の改善登録プロセス中のユーザアカウント処理の舞台裏プロセスの改善には、ユーザが CWA セットアッププロセスに 1 時間以上残っている場合にトークンを更新するプロセスが含まれています



== CWMS 5.2 リリース： Thurs. 、 2019 年 5 月 23 日

コンポーネント： 5.2 Cloud Workspace Management Suite 、 2019 年 5 月 23 日（木）午後 10 時から 23 時（東部標準時）：エンドユーザ向けの Cloud Workspace デスクトップとアプリケーションサービスへのアクセスが中断されないままになります。Cloud Workspace Management Suite へのアクセスは引き続き可能です。



=== 5.2 Cloud Workspace Management Suite の略

ワークスペースモジュールの [AVD] タブの改善されたリンク Data Center モジュールからワークスペースへのリンクをクリックしても、プライマリ管理者の連絡先情報を更新するとそのワークスペースバグ修正が削除されるシナリオのワークスペースバグ修正に移動しない場合 プライマリ管理者として指定します



== CWMS 5.2 リリース： Thurs. 、 2019 年 5 月 9 日

コンポーネント： 5.2 Cloud Workspace Management Suite 、 2019 年 5 月 9 日（木）午後 10 時 ~ 午後 11 時の東部への影響：エンドユーザ向けのクラウドワークスペースデスクトップおよびアプリケーションサービスへのアクセスが中断されないままとなります。Cloud Workspace Management Suite へのアクセスは引き続き可能です。



=== 5.2 Cloud Workspace のツールとサービス

数百 ~ 数千台の VM を含む環境での拡張性の向上



== CWMS 5.2 リリース： Thurs. 、 2019 年 4 月 25 日

コンポーネント： 5.2 Cloud Workspace Management Suite 、 2019 年 4 月 25 日（木）午後 10 時 ~ 午後 11 時（東部標準時）：エンドユーザ向けの Cloud Workspace デスクトップとアプリケーションサービスへのアクセスが中断されないままになります。Cloud Workspace Management Suite へのアクセスは引き続き可能です。



=== 5.2 Cloud Workspace Management Suite の略

インターフェイスの改善– Azure または GCP のサーバでバックアップが有効になっていない場合は、サーバの [ バックアップ ] セクションからサイズ列を削除します



=== 5.2 Cloud Workspace のツールとサービス

リソースの変更後に RDP サーバや HTML5 ゲートウェイサーバのリソースを変更してもオンラインに戻らないシナリオに対するバグ修正



=== 5.2 REST API

シナリオに関係なく、最初の MFA 設定の処理が改善されました



=== 5.2 CWA のセットアップ

既存の CWMS アカウントのサポート。間接 CSP が正しくプロビジョニングし、既存パートナーのプロセスを簡素化 Azure Active Directory ドメインサービスの追加検証を行います。 Azure Active Directory ドメインサービスが選択されていても、すでに使用されている場合は、エラーが表示されます



== CWMS 5.2 リリース： Thurs. 、 2019 年 4 月 11 日

コンポーネント： 5.2 Cloud Workspace Management Suite 、 2019 年 4 月 11 日（木）午後 10 時 ~ 午後 11 時の東部への影響：エンドユーザ向けの Cloud Workspace デスクトップとアプリケーションサービスへのアクセスが中断されないままになります。Cloud Workspace Management Suite へのアクセスは引き続き可能です。



=== 5.2 Cloud Workspace Management Suite の略

Provisioning Collections のバグ修正–デスクトップアイコンが表示されないアプリケーションで Provisioning Collection を保存すると、 CWMS のバグ修正でエラーが表示されなくなります。 CWMS から停止したプラットフォームサーバを起動する問題を解決すると、パートナーが存在しないためエラーが表示されました コードが添付されました



=== 5.2 Cloud Workspace のツールとサービス

vCloud 環境でのサーバの削除に関する安定性の強化– 1 つの vApp で複数の FMS が検出された場合、 vApp を削除する代わりに VM を削除する方法ワイルドカード証明書をインストールしないオプションを追加する AzureAD のサーバリソースレポートでの TSD サーバのクローニングの改善–複数の IP アドレスを持つサーバの処理複数の IP アドレスを持つサーバのバグ修正のシナリオのリストの場合 Azure Classic のプレフィックスを使用して VM をクローニングしようとしたときに、 AzureRM でのサーバのバックアップがレビュー用にロードされなかった（すべての新規および最近の導入で AzureRM を使用） Server 2008 R2 の Server Resource Report で DNS エラーのバグ修正が正しく報告されない原因 Server Resource Report for not sending the Company Resource report in the event that a VM deleted from the hypervisor （ but not from AD ） および CWMS がハイパーバイザー自体で Azure バックアップを検出できない（ AzureRM 環境でのみ）



=== 5.2 CWA のセットアップ

プロビジョニング対象として選択したリージョンで Azure Active Directory ドメインサービスが使用可能であることを検証する方法の追加一部のシナリオで DNS タイムアウトの問題を解決するための追加チェックを追加 CMGR1 導入のターゲットとして 2 秒を削除します。これは、導入プロセスの速度が低下しているためです



== CWMS 5.2 リリース： Thurs. 、 2019 年 3 月 28 日

コンポーネント： 5.2 Cloud Workspace Management Suite 、 2019 年 3 月 28 日（木）午後 10 時から 23 時（東部標準時）：エンドユーザ向けの Cloud Workspace デスクトップとアプリケーションサービスへのアクセスが中断されないままになります。Cloud Workspace Management Suite へのアクセスは引き続き可能です。



=== 5.2 Cloud Workspace Management Suite の略

CWMS インターフェイスに Azure Virtual Desktop セクションを追加すると、 CWMS 管理者は、カスタム App Catalog でアプリケーションを更新するときに、 [ 設定 ] -> [ ロゴ ] [ 外部 ID の追加要件 ] の下に会社のロゴを設定できなくなります



=== 5.2 Cloud Workspace のツールとサービス

Azure 向けクラウドワークスペース（ CWA ）の導入プロセスのさらなる合理化と改善 Azure RM 環境でプレミアムストレージを使用して VM を作成する必要がなくなり、アプリケーション使用状況追跡レポートで使用状況データが収集されないシナリオのサブセットで問題が解決されます HTML5 ポータルサーバで証明書を更新するとエラーが発生する問題は、 HTML5 ポータルサーバライセンスのバグ修正でパスワード有効期限通知が更新され、 Azure Active Directory ドメインサービスの使用時にパスワードが更新されませんパスワード有効期限通知がログファイルを書き込む場所を調整しました



=== 5.2 REST API

データセンターモジュールでプラットフォームサーバ（顧客サーバではない）を起動 / 停止するためのバグ修正



=== 5.2 CWA のセットアップ

導入時の FTP ロール設定の改善メカニズムが改善され、管理者が CWA セットアッププロセスにアクセスするたびに最新リリースを確認できるようになりました。導入時のバグ修正時に、導入時にタイムアウトになる要素の処理が改善されました。これは、導入時に誤って Azure AD を使用するようタグ付けられたシナリオ



== CWMS 5.2 マイナーリリース： Thurs 、 2019 年 3 月 14 日

コンポーネント： 5.2 Cloud Workspace Management Suite 、 2019 年 3 月 14 日（木）午後 10 時から 23 時（東部標準時）：エンドユーザ向けの Cloud Workspace デスクトップとアプリケーションサービスへのアクセスが中断されないままになります。Cloud Workspace Management Suite へのアクセスは引き続き可能です。



=== 5.2 Cloud Workspace Management Suite の略

「アプリケーション監視」機能の名前を「アプリケーション使用状況追跡」に変更スクリプト化イベントの検索を更新しても、選択した開始日または終了日を再使用しない修正を適用デフォルトファイル監査を現在の日付の 1 日前に設定した日付フィルタで開始します。 バックアップをサーバにリストアするときに意図したとおりに機能していなかった場合に、 Azure の Integrated Backups にバグ修正を返したデータ量を合理化することで、アプリケーションサービスに属するクライアントを更新するときに、アプリケーションエラープロンプトが解決します



=== 5.2 REST API

Azure Safeguard – Azure AD ユーザーを追加する際に、アカウントにメールアドレスがまだ追加されていないことを確認します。バグ修正–クライアントのアプリケーションを追加し、同時にグループを作成する場合、 サーバーが再起動された後も確実に適用されることを保証する RDSH サーバーへのアクセスを無効にするときに、グループにアプリケーションを追加するときのシナリオのサブセットに対する一般的な改善 CWA ワークフロー自動化バグ修正の一般的な改善 そのグループの他のユーザー



=== 5.2 CWA のセットアップ

デグレードされたレガシー MobileDrive サービスの導入プロセス中にサブスクリプションのリストの更新オプションを追加します。このリストには、 Azure の自動保護機能とチェック機能が追加されています



== CWMS 5.2 マイナーリリース： Thurs. 、 2019 年 2 月 28 日

コンポーネント： 5.2 Cloud Workspace Management Suite 、 2019 年 2 月 28 日（木）午後 10 時 ~ 午後 11 時の東部への影響：エンドユーザ向けの Cloud Workspace デスクトップとアプリケーションサービスへのアクセスが中断されないままになります。Cloud Workspace Management Suite へのアクセスは引き続き可能です。



=== 5.2 Cloud Workspace Management Suite の略

CWMS インターフェイスでユーザの [VDI ユーザ ] チェックボックスをオフにしたときの分かりやすさと確認メッセージ（ VDI ユーザのサーバを削除）、およびタイムスタンプ処理に対するサーババックエンドの改善を削除しない場合の処理方法を改善しました



=== 5.2 Cloud Workspace のツールとサービス

Azure Domain Services のライセンスサーバ名の設定を更新しました。プロセスの改善により、 Cloud Workspace にログインした後でユーザが自分のパスワードを変更できるようになりました。まれな設定が有効になっている場合は、ネイティブの 2FA の CloudJumper イメージバグ修正を反映するように、ネイティブの 2FA が更新されました



=== 5.2 CWA のセットアップ

CWA セットアップウィザードのその他のヘルプ / サポートコンテンツ CWA セットアップウィザードに契約条件と価格を追加 CWA セットアップウィザードの機能強化により、サブスクリプションのクォータおよび権限を検出するメカニズムが改善されました。 Azure Active Directory ドメインサービスベースの展開の展開を、ストレージアカウント名形式のバグフィックスを FTP サーバ用に舞台裏で改善しました シナリオのサブセット内の設定



== CWMS 5.2 マイナーリリース： Thurs. 、 2019 年 2 月 14 日

コンポーネント： 5.2 Cloud Workspace Management Suite 、 2019 年 2 月 14 日（木）午後 10 時 ~ 午後 11 時の東部への影響：エンドユーザ向けの Cloud Workspace デスクトップとアプリケーションサービスへのアクセスが中断されないままになります。Cloud Workspace Management Suite へのアクセスは引き続き可能です。



=== 5.2 Cloud Workspace Management Suite の略

ユーザー管理アクションのパフォーマンスの向上データセンタータスク履歴のグループに変更を要求したユーザーを表示するための追加ログ機能が有効になっているアプリケーションが一部のシナリオで表示されていなかった場合は、標準 App Catalog の問題が解決動的で問題が解決されます 同じ名前の 2 つのアプリケーションが CWMS 5.1 インターフェイスから SDDC 作成ウィザードを削除する * 5.1 にある SDDC を実行していて、新しい SDDC をプロビジョニングする場合、エラーが表示されるプロビジョニング CWMS 5.2 へのアップグレードをスケジュールするには、 support@cloudjumper.com に連絡してください。 CWMS の API ユーザ作成画面でスペルエラーを修正してください



=== 5.2 Cloud Workspace のツールとサービス

vCloud ベースの SDDC では、 vCloud ベースの SDDC で接続が期限切れになった場合にハイパーバイザーに再ログインします。 CloudJumper の管理アクセスの制限が改善され、サーバのブートを待機するときにデフォルトのタイムアウトが長くなります



=== 5.2 REST API

CWMS の 5.1 インターフェイスを使用して新しい SDDC をプロビジョニングすると、「 CWMS の v5.2 を使用している場合にのみ、新しいデータセンターの作成がサポートされます」というメッセージが表示されます。



=== 5.2 CWA のセットアップ

自動エラー処理が改善されました



== CWMS 5.2 マイナーリリース： Thurs 、 2019 年 1 月 31 日

コンポーネント： 5.2 Cloud Workspace Management Suite 、 2019 年 1 月 31 日（木）午後 10 時 ~ 午後 11 時の東部への影響：エンドユーザ向けの Cloud Workspace デスクトップとアプリケーションサービスへのアクセスが中断されないままになります。Cloud Workspace Management Suite へのアクセスは引き続き可能です。



=== 5.2 Cloud Workspace Management Suite の略

Cloud Workspace クライアントの接続情報を Cloud Workspace クライアントの概要セクションに追加 Azure AD テナント ID を入力できる CWMS アカウント設定に編集可能フィールドを追加 Azure AD テナント ID を入力できる最新バージョンの Microsoft Standard Storage を新しい Azure 環境で使用 Azure 統合の向上、 Azure 環境で統合バックアップを保持する必要があるアプリケーションサービスの動的プロビジョニングの処理を 1 日以上向上アプリケーションサービスの展開の動的プロビジョニングでは、アプリケーションがユーザーにプロビジョニングされていることを示すサーバーモジュールのセクションに、サーバーストレージがインベントリされる日付を追加します ユーザーが VDI ユーザーの場合、ユーザーのステータスはまだ保留中のクラウドワークスペースです。サーバーが VDI ユーザーの場合は、ユーザーページに VDI サーバーを表示します。 ユーザ名に関連付けられた未完了のサービスボードタスクがある場合に、サーバページにユーザを表示すると、その VM へのリモートアクセスが CWMS から失敗する特定のシナリオで、問題を解決します



=== 5.2 Cloud Workspace のツールとサービス

ユーザーが 1 日中ログインするときのライブスケーリングの処理が改善されました今後の Wake on Demand の機能強化のための自動化の前提条件追加今後のワークロードスケジュールの改善のための自動化の前提条件問題は、 VDI サーバー用の Windows 10 を使用して Azure Active のリモートレジストリサービスを適切に有効にできなかった場合に解決 ディレクトリドメインサービスの展開では、問題サーバで Windows 10 を使用する が、 Azure Active Directory ドメインサービスの展開でローカルリモートデスクトップユーザグループのセキュリティグループを適切に設定していなかった場合、強制ではなく有効にしても動作が実行されないように PCI 準拠設定を変更します 既定の構成設定では、ワークロードのスケジューリングで問題が解決されるため、ユーザーが Wake on Demand を有効にしてログアウトすると、サーバーの電源がオフになるようにスケジュールされている場合にサーバーの電源を切ることができます。 ProfitBricks パブリッククラウドでサーバーをクローニングするときにバグを修正するクローニングサーバーをチェックするバグ VDI ユーザシナリオでサーバ名へのサーバプレフィックスが重複しない有効なプロビジョニングコレクションを使用していないキャッシュされた顧客コードに対するチェックインレポートを夜間に追加する VM がハイパーバイザーにない場合、および CWAgent に更新解決問題が必要な場合の例外処理の改善 パスワード失効通知を使用してパスワードをリセットし、パスワード履歴を正しく適用する



=== CWA 設定

SMTP 設定を自動的に構成するオプションを実装する場所リストの検証オプションを追加して、サブスクリプションに十分なクォータがあるかどうか、および選択した Azure リージョンに追加された機能で VM を作成するための十分な権限があるかどうかをチェックし、の最後に管理者権限を持つ不要な CloudWorkspace や他のサービスアカウントを削除 Azure のプロビジョニングプロセスは、手動での DNS 証明書のアップロードが検証されたことをユーザーに通知します。特定のシナリオでは、 ThinPrint のインストールが意図したとおりにインストールされない問題が解決されました



== CWMS 5.2 マイナーリリース： Thurs. 、 2019 年 1 月 17 日

コンポーネント： 5.2 Cloud Workspace Management Suite 、 2019 年 1 月 17 日（木）午後 10 時 ~ 午後 11 時の東部への影響：エンドユーザ向けのクラウドワークスペースデスクトップおよびアプリケーションサービスへのアクセスが中断されないままとなります。Cloud Workspace Management Suite へのアクセスは引き続き可能です。



=== 5.2 Cloud Workspace Management Suite の略

ワークロードスケジューリングインターフェイスでは、最初の列に概要が表示され、「 Scheduling 」の名前を「 Custom Scheduling 」バグフィックスに変更して、 Azure 展開のプラットフォームサーバのバックアップを表示します。バグフィックスは、組織がそうでないアプリケーションサービスのエンドユーザの自己管理のシナリオに適用されます クラウドワークスペースサービスを設定します



=== 5.2 Cloud Workspace のツールとサービス

PCI v3 準拠のセキュリティ強化のサポートを追加 : 新しい CWMS の導入では、ローカル管理者とCWAgent プロセスを実行するドメイン管理者。AzureRM 環境での Windows Server 2019 のサポート * 注： Microsoft は、このバージョンでは Microsoft Office をサポートしていませんが、 Wake on Demand ユーザーの処理は改善されています。組織が VM の電源をオフにする予定で、 Wake on Demand を使用しているユーザーは、 VM のクローン作成時に組織の仮想マシンの安定性向上を停止しないでください。クローン VM から作成された新しく作成された仮想マシンから、コネクションブローカーなどの役割を削除します。ThinPrint ライセンスサーバの役割をインストールするためのプロセスの改善 AzureRM テンプレートの処理を改善–実行されているハードウェアに基づいて、 Azure で VM に使用可能なすべてのテンプレートを返却します。 テナントの Azure リージョンで使用可能なテンプレートだけでなく、 vSphere 展開の自動テストを改善したには、の特定のシナリオでのクローンサーバのバグ修正のシナリオの限定されたサブセットにある「 ThinPrint ライセンスサーバが Live Scaling のバグ修正」がインストールされているかどうかを確認するための夜間電子メールレポートが含まれます vCloud の導入事例 AzureRM の導入における VM 名プレフィックスのバグ修正 Google Cloud Platform でカスタムマシンサイズを使用する際のレポートエラー修正バグ ThinPrint 機能が有効なレポートユーザのバグ修正 AzureRM で使用可能なテンプレートのリストから Windows の中国語版を除外



=== CWA 設定

最低限必要な文字数を満たすパスワードが受け入れられないシナリオを修正する CSP アップデートのテナント選択プロセス中に、 ID 列をカスタマードメインに変更し、クレジットカードの入力を合理化するサインアッププロセスに進みます



== CWMS 5.2 マイナーリリース： Thurs 、 2018 年 12 月 20 日

コンポーネント： 5.2 Cloud Workspace Management Suite 、 2018 年 12 月 20 日（木）午後 10 時 ~ 午後 11 時の東部への影響：エンドユーザ向けのクラウドワークスペースデスクトップおよびアプリケーションサービスへのアクセスは中断されません。Cloud Workspace Management Suite へのアクセスは引き続き可能です。



=== 5.2 Cloud Workspace のセットアップ

単一サーバの導入時に FTP DNS 登録の機能を追加し、自動 SSL を選択した場合に Azure AD 情報を入力するプロセスを自動化しました。（ Tenantid 、 ClientID 、 Key ）をバックエンドテーブルにインポート自動インストールプロセスでは、 10 ではなく ThinPrint License Server 11 がインストールされるようになりました



=== 5.2 CWA のセットアップ

登録プロセスが完了したら、管理者をサインインページにリダイレクトした問題を修正します



== CWMS 5.2 マイナーリリース： Thurs 、 2018 年 12 月 6 日

コンポーネント： 5.2 Cloud Workspace Management Suite 、 2018 年 12 月 6 日（木）午後 10 時 ~ 午後 11 時の東部への影響：エンドユーザ向けのクラウドワークスペースデスクトップおよびアプリケーションサービスへのアクセスは中断されません。Cloud Workspace Management Suite へのアクセスは引き続き可能です。



=== 5.2 Cloud Workspace ツールとサービス

Win10 OS を使用したサーバの作成のサポートが向上ハイパーバイザーから VM をロードする際の速度が向上 Azure でのサーバの作成時に使用できる正しいストレージタイプを返す日常レポートのログをコントロールプレーンのバックエンドに追加する一時ドライブが Azure で自動的に拡張されるシナリオを回避します Azure Active Directory ドメインサービスを使用している場合、複数の MGR サーバが設定されている場合、 GCP Bug fix for not automatically expanding a drive in GCP Bug fix for deployment automation when using Azure Active Directory Domain Services if multiple MGR severs are configured 、 メモパブリッククラウド（ Azure 、 GCP ）の自動テスト用のナイトリーレポートバグ修正 VMware 環境でのバックアップバグ修正 HyperV 導入を介して作成された新しい VM のディスクスペースを特定するための修正 AD ルート OU が設定されていないハイパーバイザーをベースにしてサーバーをクローニングする際のサーバーデータ収集用のバグ修正



=== 5.2 REST API

パブリッククラウド配置でマシンシリーズのサポートを有効にすると、 SDDC で追加された DataCollectedDateUTC のデフォルトのリソース割り当てを無効にして、サーバのストレージの詳細を表示リソースの値を計算する機能を追加する詳細なユーザ接続ステータスを取得するための新しいメソッドを追加 CWMS でエラーを表示します 管理者権限を持つユーザを削除すると、データを有効にしたアプリケーションサービスのドライブマッピングを使用した固定問題が表示されない問題 CWA 経由でインポートされたクライアントまたはユーザを更新する固定問題新しいユーザが作成され、アプリケーションが割り当てられたときに CWMS 経由でクライアントまたはユーザを更新する [ すべてのユーザー ] グループでは、新しいユーザーはアプリケーションショートカットを受け取りません。



== CWMS 5.2 マイナーリリース： Thurs 、 2018 年 11 月 1 日

コンポーネント： 5.2 Cloud Workspace Management Suite 、 2018 年 11 月 1 日（木）午後 10 時 ~ 午後 11 時の東部への影響：エンドユーザ向けのクラウドワークスペースデスクトップおよびアプリケーションサービスへのアクセスは中断されません。Cloud Workspace Management Suite へのアクセスは引き続き可能です。



=== 5.2 Cloud Workspace Management Suite の略

CRA 展開での特定の使用例に対する統合バックアップバグ修正バグ修正



=== 5.2 Cloud Workspace のツールとサービス

複数サイトの Active Directory トポロジのサーバの作成時に Azure ARM 環境で使用可能なストレージタイプを返す機能を有効にするマルチサイトの Active Directory トポロジのサポート問題 with TestVDCTools when using Azure Active Directory Domain Servce Bug fix for nightly email reports when AD root OU is blank



=== 5.2 REST API

Azure Active Directory ドメインサービスのロック解除をサポートします。注：レプリケーションにより、最大 20 分程度の遅延が生じる場合があります。



== CWMS 5.2 マイナーリリース： Thurs 、 2018 年 10 月 18 日

コンポーネント： 5.2 Cloud Workspace Management Suite 、 2018 年 10 月 18 日（木）午後 10 時 ~ 午後 11 時の東部への影響：エンドユーザ向けのクラウドワークスペースデスクトップおよびアプリケーションサービスへのアクセスは中断されません。Cloud Workspace Management Suite へのアクセスは引き続き可能です。



=== 5.2 Cloud Workspace Management Suite の略

データセンターウィザードで、 ワイルドカード証明書の検証の有効化バックグラウンド改善とバグ修正アプリケーションテーブルでの検索機能の追加アプリケーションテーブルでのソートの向上データセンタープロビジョニングプロセスでの DNS 登録の完了の詳細データの追加動的 API コール応答にすべてのサブパートナーユーザとグループが含まれます アプリサービス特定のインスタンスでテナントの移行モードが維持されないというバグを修正する追加電源オンサーバーを追加 サーバあたりの共有ユーザ数とサーバあたりの最大共有ユーザ数のライブスケーリングの詳細新しいデータセンターウィザードを使用したプロビジョニング時に、ワイルドカード証明書テストに DNS 検証を追加します



=== 5.2 Cloud Workspace ツールとサービス

オプションを有効にして、 VM シリーズごとにグループ化されたすべての VM サイズを返すアプリケーションサービスユーザの計算時にハイパーバイザーで使用可能なすべての VM サイズを返す CWMGR1 の自動リソース更新の Enable オプションにワイルドカード証明書ステータス DataCenterResources Report 将来の DNS 拡張バグ修正を有効にする– GCP 展開での自動ドライブ拡張の修正



=== 5.2 REST API

クライアント / ユーザーをリストする際のパフォーマンスの向上新しいライブスケーリング機能のサポート– ExtraPoweredOnServers 、 SharedUsersPerServer 、 MaxSharedUsersPerServer API の構成では、すべてのパートナークライアントのユーザーアクティビティデータを取得するための新しいプラットフォーム展開の作成時にワイルドカード証明書ドメインを検証する機能がサポートされるようになりました

Known 問題： Azure ARM 展開内のリソースプールのサイジングに「 Active Users 」または「 User Count 」の動的割り当て方法を使用すると、「 Computed Resource per Server 」の概要で、正しい標準 D シリーズタイプではなく、シリーズタイプとして「 Machine Size 」が誤って表示されます。



== CWMS 5.2 マイナーリリース： Thurs 、 2018 年 9 月 27 日

コンポーネント： 5.2 Cloud Workspace Management Suite 、対象期間： 2018 年 9 月 27 日（木）午後 10 時 ~ 午後 11 時（東部標準時）：エンドユーザ向けのクラウドワークスペースデスクトップおよびアプリケーションサービスへのアクセスは中断されません。Cloud Workspace Management Suite へのアクセスは引き続き可能です。



=== 5.2 Cloud Workspace Management Suite の略

コレクション VM をキャッシュにプロビジョニングする際の表示を簡素化 App Services を管理するときに、表示ひれを修正します



=== 5.2 Cloud Workspace のツールとサービス

エンドユーザ MFA 更新 API が最新の Azure RM 更新テストと連携して、最新の API を使用するためのあいまいなユースケースのバグ修正パワーユーザ用語を VDI ユーザ更新電子メールレポートに置き換えることで、サーバの CPU と RAM を追加することができます アドレスレポートを更新します。 dcnotifications@independenceit.com メッセージではなく、 dcnotfications@cloudjumper.com から送信される メッセージでは、サーバごとのユーザー定義と追加の VM をライブスケーリングによるパフォーマンスの向上により維持できます。停止された SDDC/ 展開セキュリティの強化を開始するときに、追加の VM を有効にします。複数の SDDC/ 展開を持つパートナーが 1 つから接続することを また、安定性の向上–自動化によってユーザ数を返すことができない場合は、リソースカウントのマイナーな外観の強化を変更しないでください



== CWMS 5.2 マイナーリリース： Thurs 、 2018 年 9 月 6 日

コンポーネント： 5.2 Cloud Workspace Management Suite 、 2018 年 9 月 6 日（木）午後 10 時 ~ 午後 11 時の東部への影響：エンドユーザ向けのクラウドワークスペースデスクトップおよびアプリケーションサービスへのアクセスは中断されません。Cloud Workspace Management Suite へのアクセスは引き続き可能です。



=== 5.2 Cloud Workspace Management Suite の略

カスタムアプリカタログでサブパートナーを検索できるようになりましたデータセンターモジュールの画面を更新するとエラープロンプトが表示されるため、最大フォルダー名のサイズ制限が除去され、フォルダーを参照しやすくなり、 VM のリソースカウントが確実になるというバグが修正されました は、指定された最小 CPU 値および RAM 値の再フレーズ Power User Terminology to VDI User Data Center Creation ウィザードでのサーバー名表示の改善に成功したにもかかわらず、一般的なエラーが表示されるというエラーを修正しました。アカウントの有効期限が保存された有効期限を表示しません を選択します



=== 5.2 Cloud Workspace のツールとサービス

電子メールを選択したユーザーがコードを受信できない場合がある問題のバグを修正ユーザー数リソース割り当てタイプに CPU と RAM を追加入力できるようにするオートメーションエンジンがすべての種類のマシンに電力を供給しなかったというバグを修正しました自動化エンジンが、時々原因を実行するタイミング を修正しました エラーアウトするためのサーバのクローニング FTP サーバでワイルドカード証明書を手動でインストールしたときに、ワイルドカード証明書の更新後に古い証明書をパージするプロセスが追加されました。問題は、 Data Enabled Application Services を使用している場合、 X: ドライブがエンドユーザに常にマッピングされるとは限りません。



== CWMS 5.2 General Availability Release ： Thurs 、 2018 年 8 月 10 日

コンポーネント： 5.2 Cloud Workspace Management Suite 、 2018 年 8 月 10 日（木）午後 10 時（東部標準時）：エンドユーザ向けのクラウドワークスペースデスクトップおよびアプリケーションサービスへのアクセスは中断されません。Cloud Workspace Management Suite へのアクセスは引き続き可能です。



=== 5.2 Cloud Workspace Management Suite の略

Web インターフェイスコンポーネントをリリースして、上記の概要で説明した機能を有効にします



=== 5.2 Cloud Workspace のツールとサービス

バックエンドツールをリリースして、上記の概要にある機能を有効にします



=== 5.2 REST API

....
Release API to production to enable the features found in the overview above
....