= 日時： 2020 年 7 月 29 日（木）午後 11 時（東部標準時




== 日時： 2020 年 7 月 29 日（木）午後 11 時（東部標準時

影響： _ ユーザーは、次回起動時に VDS Client for Windows を更新します



=== 改善

* インストールプロセスが合理化されます。新しいエンドユーザーは、 VDS Client for Windows をインストールする際に、契約条件に同意する必要がなくなります
* インストールプロセス中に確認を追加して、エンドユーザーのデバイスが自動更新の発信元の場所にアクセスできることを確認します




== 日付： 2020 年 5 月 27 日（木）午後 11 時（東部標準時

影響：ユーザーは、次回 RDP クライアントを起動するときに RDP クライアントの更新を確認できます



=== バグ修正

* 指定されたパスワードが長すぎる場合に表示されるエラーメッセージの明確さが向上しました




== 日付： 2020 年 5 月 13 日（木）午後 11 時（東部標準時

影響：ユーザーは、次回 RDP クライアントを起動するときに RDP クライアントの更新を確認できます



=== 改善

* 自動化機能を追加して、エンドユーザのリソースの可用性を確保します




=== 更新

* 自動更新にアクセスするために必要な URL が変更されています。インバウンドトラフィックをアクティブに保護していない場合は、変更を行う必要はありません。
+
** エンドユーザは、変更がなくてもデスクトップに引き続きアクセスできます
** 組織は、着信トラフィックを積極的に保護するために、エンドユーザデバイスが上記の新しい URL にアクセスできるようにして、自動更新に確実にアクセスできるようにする必要があります
** 更新の現在のソースは次のとおりです。
+
*** プライマリ： cwc.cloudworkspace.com
*** セカンダリ： cloudjumper.com


** 更新の新しいソースは次のとおりです。
+
*** プライマリ： bin.vdsclient.app
*** セカンダリ： cwc.cloudworkspace.com


** Cloud Workspace Client for Windows を新規ユーザーがインストールした場合も、リストされている URL にアクセスする必要があります link:https://docs.netapp.com/us-en/virtual-desktop-service/Reference.end_user_access.html#remote-desktop-services["こちらをご覧ください"]






== 日時： 2020 年 4 月 29 日（木）午後 11 時（東部標準時

影響：次回 RDP クライアントを起動すると、 RDP クライアントの更新が表示されます

（このリリースでは更新なし）



== 日付： 2020 年 4 月 15 日（木）午後 11 時（東部標準時

影響：ユーザーは、次回 RDP クライアントを起動するときに RDP クライアントの更新を確認できます



=== バグ修正

* ネットワークテストの結果が意図したとおりに送信されない問題を解決します




== 日付： 2020 年 4 月 1 日（木）午後 11 時（東部標準時

影響：ユーザーは、次回 RDP クライアントを起動するときに RDP クライアントの更新を確認できます



=== 改善

* RemoteApp アプリケーションへの更新 - ユーザーが個々のアプリケーションを起動するときに資格情報の入力を求めなくなりました
* エンドユーザーが、 ThinPrint と Windows プリンタのリダイレクトを使用して印刷を切り替えることができるようにするためのアップデート
* Windows Designer ユーザ用の VDS クライアントが印刷リダイレクトサービスを除外できるようにするための更新




== VDS 5.4 リリース： Thurs. 、 2021 年 1 月 21 日

_Components ： _5.4 Virtual Desktop Service_When ： _Thursday January 21, 2021 の午後 10 時 ～ 午後 11 時 East_Impact ： _Users は、次回起動時に RDP クライアントの更新を確認します



=== 改善

* エンドユーザーの操作性が向上し、外部ドメインからインポートされたユーザーの処理が向上しました




== 日付： 2020 年 6 月 11 日（木）午後 11 時（東部標準時

影響：ユーザーは、次回 RDP クライアントを起動するときに RDP クライアントの更新を確認できます



=== 改善

* インストール可能な最新の AVD RDP クライアントを更新します




== 日付： 2020 年 5 月 28 日（木）午後 11 時（東部標準時

影響：ユーザーは、次回 RDP クライアントを起動するときに RDP クライアントの更新を確認できます



=== 改善

* ネットアップのブランド力やフレージングを反映するように更新されました。注：この新しいブランディングは、次のものに適用されます。
+
** 新しい VDS クライアントのダウンロード
** Windows インストール用の既存の未編集 VDS クライアント
** 既存のカスタム編集 / ブランドのクライアントは、カスタマイズされていない場合にのみ新しいバナーイメージを受け取ります。バナーイメージがカスタマイズされている場合は、そのまま残ります。その他の色およびフレージングはすべて同じままです。






== 日付： 2020 年 5 月 14 日（木）午後 11 時（東部標準時

影響：ユーザーは、次回 RDP クライアントを起動するときに RDP クライアントの更新を確認できます

* このリリースサイクルの更新はありません。




== 日付： 2020 年 4 月 30 日（木）午後 11 時（東部標準時

影響：ユーザーは、次回 RDP クライアントを起動するときに RDP クライアントの更新を確認できます



=== バグ修正

* セルフサービスパスワードリセットが表示されなかったシナリオの一部に対するバグ修正




== 日付： 2020 年 4 月 16 日（木）午後 11 時（東部標準時

影響：ユーザーは、次回 RDP クライアントを起動するときに RDP クライアントの更新を確認できます

* このリリースサイクルの更新はありません。




== 日付： 2020 年 4 月 2 日（木）午後 11 時（東部標準時

影響：ユーザーは、次回 RDP クライアントを起動するときに RDP クライアントの更新を確認できます

* このリリースサイクルの更新はありません。




== 日時： 2020 年 3 月 19 日（木）午後 11 時（東部標準時

影響：ユーザーは、次回 RDP クライアントを起動するときに RDP クライアントの更新を確認できます

* このリリースサイクルの更新はありません。




== 日時： 2020 年 3 月 5 日（木）午後 10 時（東部標準時

影響：ユーザーは、次回 RDP クライアントを起動するときに RDP クライアントの更新を確認できます



=== 改善

* RDP プロトコルを使用したフリンジバグの正常な処理。 RDS ゲートウェイ上でレガシー資格情報タイプと最新のパッチが混在していると、セッションホストに接続できなくなります
+
** エンドユーザーのワークステーションが（外部管理者、社内顧客管理者、またはワークステーションのデフォルト設定を使用して）レガシークレデンシャルタイプを使用するように設定されている場合、このリリースより前にユーザーに影響を与える可能性はほとんどありません


* クラウドワークスペースクライアントデザイナの [ 情報 ] ボタンを更新されたドキュメントソースにポイントします
* クラウドワークスペースクライアントデザイナの自動更新プロセスが改善されました




== 日時： 2020 年 2 月 20 日（木）午後 10 時（東部標準時

影響：ユーザーは、次回 RDP クライアントを起動するときに RDP クライアントの更新を確認できます



=== 改善

* セキュリティ、安定性、拡張性をプロアクティブに強化




=== 考慮事項

* ユーザーが 4/2 より前に起動している限り、 Cloud Workspace Client for Windows は引き続き自動更新を実行します。4/2 より前のバージョンの Windows 用 Cloud Workspace クライアントを起動しなかった場合、デスクトップへの接続は機能しますが、自動更新機能を再開するには、 Cloud Workspace クライアント for Windows をアンインストールして再インストールする必要があります。
* 組織で Web フィルタリングを使用している場合は、自動更新機能が維持されるように、 cwc.cloudworkspace.com および cwc-cloud.cloudworkspace.com へのセーフリストアクセスを行ってください




== 日付： 2020 年 1 月 9 日（木）午後 11 時（東部標準時

影響：ユーザーは、次回 RDP クライアントを起動するときに RDP クライアントの更新を確認できます

* このリリースサイクルの更新はありません。




== 日付： 2019 年 12 月 19 日（木）午後 11 時（東部標準時

影響：ユーザーは、次回 RDP クライアントを起動するときに RDP クライアントの更新を確認できます

* このリリースサイクルの更新はありません。




== 日付： 2019 年 12 月 2 日月曜日の東部標準時

影響：ユーザーは、次回 RDP クライアントを起動するときに RDP クライアントの更新を確認できます

* このリリースサイクルの更新はありません。




== 日付： 2019 年 11 月 14 日（木）午後 11 時（東部標準時

影響：ユーザーは、次回 RDP クライアントを起動するときに RDP クライアントの更新を確認できます



=== 改善

* ユーザーが「サービスは現在オフラインです」というメッセージを表示する理由の明確さが向上しました。メッセージが表示される可能性のある原因は次のとおりです。
+
** セッションホストサーバはオフラインになるようにスケジュールされており、ユーザに Wake On Demand 権限がありません。
+
*** ユーザーが Cloud Workspace クライアントを使用していた場合は、次のように表示されます。「現在、サービスはオフラインになるようにスケジュールされています。アクセスが必要な場合は、管理者にお問い合わせください。」
*** ユーザーが HTML5 ログインポータルを使用していた場合、「サービスは現在オフラインになるようにスケジュールされています。アクセスが必要な場合は、管理者にお問い合わせください。」


** セッションホストサーバーはオンラインになるようにスケジュールされており、ユーザーに Wake On Demand 権限がありません。
+
*** ユーザーが Cloud Workspace クライアントを使用していた場合は、「サービスは現在オフラインです。アクセスが必要な場合は、管理者に問い合わせてください。」というメッセージが表示されます。
*** ユーザーが HTML5 ログインポータルを使用していた場合は、「サービスは現在オフラインです。アクセスが必要な場合は、管理者にお問い合わせください。」


** セッションホストサーバはオフラインになるようにスケジュールされており、ユーザに Wake on Demand 権限があります。
+
*** ユーザーが Cloud Workspace クライアントを使用していた場合は、「サービスは現在オフラインです。アクセスが必要な場合は、管理者に問い合わせてください。」というメッセージが表示されます。
*** ユーザーが HTML5 ログインポータルを使用していた場合、「サービスは現在オフラインになるようにスケジュールされています。[ スタート ] ボタンをクリックしてオンラインにし、接続します。」


** セッションホストサーバはオンラインになるようにスケジュールされており、ユーザに Wake on Demand 権限があります。
+
*** ユーザーが Cloud Workspace クライアントを使用していた場合は、「ワークスペースが起動するまでに 2 ～ 5 分かかります。」というメッセージが表示されます。
*** ユーザーが HTML5 ログインポータルを使用していた場合は、「サービスは現在オフラインです。[ スタート ] ボタンをクリックしてオンラインにし、接続します。」








== 日付： 2019 年 10 月 31 日（木）午後 11 時（東部標準時

影響：ユーザーは、次回 RDP クライアントを起動するときに RDP クライアントの更新を確認できます

* このリリースサイクルの更新はありません。




== 日付： 2019 年 11 月 17 日（木）午後 11 時（東部標準時

影響：ユーザーは、次回 RDP クライアントを起動するときに RDP クライアントの更新を確認できます



=== 改善

* AVD 要素の追加：




== 日付： 2019 年 10 月 3 日（木）午後 11 時（東部標準時

影響：ユーザーは、次回 RDP クライアントを起動するときに RDP クライアントの更新を確認できます



=== 改善

* コード署名証明書の処理が改善されました


バグ修正

* RemoteApp にアクセスしているユーザーにアプリケーションが割り当てられていない問題を修正します。エラーが発生しました
* 仮想デスクトップへのログイン中にユーザーがインターネット接続を失った問題を解決します




== 開催日： 2019 年 9 月 19 日（木）午後 11 時（東部標準時

影響：ユーザーは、次回 RDP クライアントを起動するときに RDP クライアントの更新を確認できます



=== 改善

* AVD 要素の追加：
+
** エンドユーザーが AVD リソースにアクセスできる場合は、 AVD タブを表示します
** AVD タブには、次のオプションがあります。
+
*** AVD RD クライアントがまだインストールされていない場合は、インストールします
*** AVD RD クライアントがインストールされている場合は、 RD クライアントを起動します
*** Web Client を起動して、 AVD HTML5 ログインページに移動します
*** [ 完了 ] をクリックして前のページに戻ります








== 日付： 2019 年 9 月 5 日（木）午後 11 時（東部標準時

影響：ユーザーは、次回 RDP クライアントを起動するときに RDP クライアントの更新を確認できます

* このリリースサイクルの更新はありません。




== 日付： 2019 年 8 月 22 日（木）午後 11 時（東部標準時

影響：ユーザーは、次回 RDP クライアントを起動するときに RDP クライアントの更新を確認できます

* このリリースサイクルの更新はありません。




== 日付： 2019 年 8 月 8 日（木）午後 11 時（東部標準時

影響：ユーザーは、次回 RDP クライアントを起動するときに RDP クライアントの更新を確認できます

* このリリースサイクルの更新はありません。




== 日付： 2019 年 7 月 25 日（木）午後 11 時（東部標準時

影響：ユーザーは、次回 RDP クライアントを起動するときに RDP クライアントの更新を確認できます

* このリリースサイクルの更新はありません。




== 日付： 2019 年 7 月 11 日（木）午後 11 時（東部標準時

影響：ユーザーは、次回 RDP クライアントを起動するときに RDP クライアントの更新を確認できます

* このリリースサイクルの更新はありません。




== 開催日： 2019 年 6 月 21 日（金）午前 4 時（東部標準時

影響：ユーザーは、次回 RDP クライアントを起動するときに RDP クライアントの更新を確認できます

* このリリースサイクルの更新はありません。




== 開催日： 2019 年 6 月 7 日（金）午前 4 時（東部標準時

影響：ユーザーは、次回 RDP クライアントを起動するときに RDP クライアントの更新を確認できます



=== 改善

* .RDP ファイルのファイルタイプの関連付けがに設定されているかどうかに関係なく、 Cloud Workspace クライアントが RDP 接続を自動的に起動できるようにします




== 開催日： 2019 年 5 月 24 日（金）午前 4 時（東部標準時

影響：ユーザーは、次回 RDP クライアントを起動するときに RDP クライアントの更新を確認できます



=== 改善

* サインイン処理のパフォーマンスが向上しました
* 起動時の負荷時間を短縮




== 開催日： 2019 年 5 月 10 日（金）午前 4 時（東部標準時

影響：ユーザーは、次回 RDP クライアントを起動するときに RDP クライアントの更新を確認できます



=== 改善

* サインイン処理のパフォーマンスが向上しました
* 起動時の負荷時間を短縮




== 開催日： 2019 年 4 月 12 日（金）午前 4 時（東部標準時

影響：ユーザーは、次回 RDP クライアントを起動するときに RDP クライアントの更新を確認できます



=== 改善

* Wake on Demand のログイン速度が向上しました
* Cloud Workspace Client for Windows が正常に起動された後、フィードバックボタンを削除してユーザーインターフェイスの領域を解放します


バグ修正

* Wake on Demand アクションが失敗した後、サインインボタンが応答しなかった問題を解決します




== 開催日： 2019 年 3 月 15 日（金）午前 4 時（東部標準時

影響：ユーザーは、次回 RDP クライアントを起動するときに RDP クライアントの更新を確認できます



=== 改善

* Cloud Workspace Client for Windows を使用している管理者が、サポート用の E メールアドレスまたは電話番号のいずれかを指定できます。両方は必要ありません
* Cloud Workspace Client で提供される HTML5 URL が有効な URL であることを確認します。有効でない場合、デフォルトで https ： // login.cloudjumper.com に設定されます
* エンドユーザにアップデートを適用するプロセスを合理化します




== 開催日： 2019 年 2 月 29 日（金）午前 4 時（東部標準時

影響：ユーザーは、次回 RDP クライアントを起動するときに RDP クライアントの更新を確認できます



=== 改善

* AppData フォルダは、 c:\users\<username> \appdata\local\RDPClient から c:\users\appdata\local\Cloud Workspace に移動されました
* ユーザーが複数のリリースでクライアントを更新していない場合に、アップグレードパスを合理化するメカニズムを実装しました
* ベータ版のクライアントで作業しているユーザーに対して、拡張ログの詳細が有効になっています


バグ修正

* 更新処理中に複数の行が表示されなくなります




== 開催日： 2019 年 2 月 15 日（金）午前 4 時（東部標準時

影響： _ ユーザーは、 RDP クライアントを起動すると、 RDP クライアントの更新を表示します



=== 改善

* リモートインストールのサイレント / サイレントインストールオプションを有効にします
+
** インストールフラグは次のとおりです。
+
*** /s または /silent または /q または /quiet
+
**** これらのフラグは、クライアントをサイレントにインストールし、バックグラウンドでインストールします。インストールの完了後、クライアントは起動しません


*** /p または / パッシブ
+
**** これらのいずれかはインストールプロセスを示しますが、入力は必要なく、インストールの完了後にクライアントが起動します


*** /nthinprint
+
**** インストールプロセスから ThinPrint を除外します






* レジストリエントリが HKLM\Software\CloudJumper\Cloud Workspace Client\Branding に追加されました。
+
** ClipboardSharingEnabled ： True/False –クリップボードのリダイレクトを許可または禁止します
** RemoteAppEnabled ： True/False – RemoteApp 機能へのアクセスを許可または禁止します
** ShowCompanyNameInTitle: 正誤–会社名を表示するかどうかを示します


* c ： \Program Files （ x86 ） \Cloud Workspace に次のファイルを追加できます。
+
** banner.jp g 、 banner.png 、 banner.gif または banner.bmp 。これがクライアントウィンドウに表示されます。
** これらの画像の比率は 21 ： 9 にする必要があります






=== バグ修正

* 登録されているシンボルが調整されました
* ヘルプページの空白の電話と電子メールのエントリが修正されました

