= 概要



NOTE: CWS の v5.0 については、今後のリリースでは繰り返しリリースされません。すべてのリリースはホットフィックスと見なされます。



== 概要

CloudJumper は、 2016 年第 4 四半期より、一般実装用の Cloud Workspace Suite 5.0 をリリースしました。このリリースでは、 CWS API と Admin Control インターフェイスの両方が更新されています。リリースは大幅に変更され、バージョン 4.x エンティティとの「下位互換性」はありません。

バージョン 4.x は、すべてのパートナー Software Defined Data Center （ SDDC ）が 5.0 プラットフォームにアップグレードされるまで引き続きサポートされます。アップグレードは、各パートナーと連携して CloudJumper によって完了し、既存のサービスは中断されません。移行に伴うアップグレード料金や導入コストは発生しません。CWS 5 は、以前のバージョンのすべての機能を引き続きサポートし、管理者とエンドユーザの両方のエクスペリエンスを向上させる新機能を拡張し、以前のリリースの Cloud Workspace Suite で導入された受賞歴のある自動化とオーケストレーションをさらに向上させます。

CWS 5.0 では、 CloudJumper はすべてのプラットフォーム API を REST API 形式に再書き込みし、以前の SOAP API を完全に廃止しました。このアップデートされたアーキテクチャにより、 CloudJumper の機能がさらに強化され、外部の開発者は Cloud Workspace をベースにサービスと製品を拡張するための環境をさらに整備することができます。



== ハイライト

* UI/UX の書き換えを完了します
* Azure AD 統合
* Azure SDDC セルフサービスの導入
* アプリケーションサービス
* リソースのスケジューリング
* Live Server Scaling –クロスプラットフォーム
* 自動サーバークローニング–クロスプラットフォーム
* クライアントごとにドライブ共有をカスタマイズします




== 主な機能：



=== Azure Active Directory （ AD ）統合

* SDDC をプライベートクラウド Active Directory として構築するか、 Microsoft Azure-AD-as-a-Service を使用します
* CWS と Office365 を組み合わせます
* Azure ベースの SSO と MFA をサポート




=== Azure SDDC セルフサービスの導入

* Azure との完全な統合
* 新しいデータセンターを迅速に導入
* クラウドワークスペースマネージド、アプリケーションサービス、プライベート Web アプリケーション、 SharePoint など、あらゆるワークロードに対応するプライベートエンタープライズクラウドを Azure 内に導入できます




=== アプリケーションサービス

* アプリケーションサイロを導入して、分離されたサービスビルディングブロックとして公開アプリケーションを実行します
* 「パブリック」アプリケーションサーバーから多くのカスタムエンティティに配信されるアプリケーション
* アプリケーションは、単一のアプリケーション専用サーバプールにインストールされます
* ユーザプロファイルとデータレイヤの要件から分離されたアプリケーション
* 拡張性に優れたアプリケーションサービスを構築
* 複数のアプリケーションサービスをユーザコレクションに統合できます
* CWS ライセンスの追跡と使用状況のレポート




=== サーバのライブスケーリング–クロスプラットフォーム

* サーバ・リソース / アクティブ・サーバのインテリジェントな自動拡張
* ユーザー負荷の変化に合わせて、動的な増減でサーバーリソースを厳密に管理します
* ワークロードの変化に応じてサーバリソースを自動的に増減




=== サーバの自動クローン作成：クロスプラットフォーム

* 定義されたユーザー数が増加するまで、サーバーの可用性が自動的に増加します
* 使用可能なリソースプールにサーバを追加します
* CWS Live Server Scaling 機能と組み合わせることで、完全に自動化された解決策を作成できます




=== リソースのスケジューリング

* 顧客ごとにサービス時間をスケジュールします
* パブリッククラウドのコスト抑制
* 使用していない場合はシステムをシャットダウンし、事前に定義されたスケジュールで再アクティブ化します

