= CWMS 5.1 マイナーリリース： 2018 年 10 月 18 日（木



NOTE: 今後、 CWMS の v5.1 には繰り返しリリースはありません。すべてのリリースはホットフィックスと見なされます。



== CWMS 5.1 マイナーリリース： 2018 年 10 月 18 日（木

コンポーネント： 5.1 Cloud Workspace Management Suite 、 2018 年 10 月 18 日（木）午後 10 時 ~ 午後 11 時の東部への影響：エンドユーザ向けの Cloud Workspace デスクトップおよびアプリケーションサービスへのアクセスは中断されません。Cloud Workspace Management Suite へのアクセスは引き続き可能です。



=== Workspace Management Suite の略

* アプリケーションテーブルに検索機能を追加します
* アプリケーションテーブルでの並べ替えが向上しました




== CWMS 5.1 マイナーリリース： Thurs. 、 2018 年 9 月 6 日

コンポーネント： 5.1 Cloud Workspace Management Suite 、 2018 年 9 月 6 日（木）午後 10 時から午後 11 時（東部標準時）：エンドユーザ向けのクラウドワークスペースデスクトップおよびアプリケーションサービスへのアクセスは中断されません。Cloud Workspace Management Suite へのアクセスは引き続き可能です。



=== 5.1 Cloud Workspace Management Suite の略

* カスタムアプリケーションカタログでサブパートナーを検索する機能が追加されました
* Data Center モジュールの画面を更新するとエラープロンプトが表示されるというバグが修正されました
* 最大フォルダ名サイズの制限を解除し、フォルダを簡単に参照できるようにします
* VM のリソース数が、指定された最小 CPU 値および RAM 値を下回ることがないようにします




=== 5.1 Cloud Workspace のツールとサービス

* 電子メールを選択したユーザーがコードを受信できないことがある MFA のバグを修正しました
* User Count リソース割り当てタイプに追加の CPU および RAM を入力できるようにします
* Server Load Allocation for Server のバグを修正しました。必要なサーバ数がオフになっている場合があります
* サーバの自動リブート時にセーフガードを追加– CwVmAutomationService がビジー状態の場合は、 20 分後に再試行します
* CWMGR1 でのワイルドカード証明書インストールの処理が改善されました
* データセンターリソースレポート内の固定データ
* RAM リソースの更新の処理が改善されました
* 使用可能なハードドライブリソースの計算が改善されました
* ProfitBricks の API v4 をサポートし、 CPU ファミリの設定を可能にします
* プロビジョニングコレクションの作成時に使用される ProfitBricks で古い一時テンプレートの削除を修正
* ProfitBricks のハイパーバイザーが VM を作成するのを待機するときのタイムアウトが長くなりました
* VdcTools の新しいバージョンをインストールする場合、自動化をより早く実行できるように、処理中にすぐに VdcToolsVersionRunningAtVdc を更新します
* RDP ゲートウェイサーバにワイルドカード証明書をインストールするときに表面化するバグを修正しました
* FTP サーバに以前手動でワイルドカード証明書をインストールすることを自動化します
* パスワードの有効期限が通知されず、ユーザにパスワードの更新を強制していないというバグが修正されました
* ファイル監査プロセスが改善され、不明なユーザーエラーが表示される頻度が減少しました
* File Audit Report でフォルダが正しく除外されないというバグが修正されました
* コネクションブローカーの証明書の期限が切れている場合に、ワイルドカード証明書をインストールする機能が追加されました
* パスワード有効期限通知のショートカットがスタートアップフォルダから削除された場合に、パスワードの有効期限通知が表示されないというバグが修正されました ( 再インストールされます ) 。
* ユーザーがログインした場合に、ワイルドカード証明書により HTML5 ポータルサーバーの更新が遅延しないというバグが修正されました
* ワイルドカード証明書で、 HTML5 ポータルサーバを最新の状態に更新する必要があるというバグが修正されました
* コネクションブローカーサーバにワイルドカード証明書をインストールすると、バグが修正されました
* ローカル VM アカウントが削除されているクローニング問題を修正しました
* クローニングサーバでテナントが移行モードになっている問題を修正
* vCloud での VM のクローニング中に、ハイパーバイザーが VM の作成に予想より長い時間を要したエラーを修正しました
* AzureRM で VM を削除すると、関連する管理対象ディスクも常に削除されるというバグを修正しました
* 2 つのビルド操作が重複しないように、問題が AzureRM で VM を作成するまれなタイミングを修正しました
* AzureRM のマシンサイズとタイプのリストを更新
* 導入時にハイパーバイザーで GCP のサブネットを設定する際にエラーが修正されました
* サーバがビジー状態のときにデータが書き込まれないようにするタイムアウトを削除することにより、監視データの保存エラーが修正されました
* 各サーバに個別にタイムゾーンを設定できるようにする機能、またはプラットフォームの自動化によって制御されない機能を追加しました
* セカンダリサイトで VM を作成するとプライマリサイトから静的 IP アドレスが返されるというバグが修正されました
* ユーザログインレポートのユーザ名のキャプチャでエラーが修正されました
* 古い監視データを削除できなかったバグを修正し、呼び出しを非同期にしてタイムアウトしないようにしました
* ワイルドカード証明書をすべてのインフラサーバに自動的にインストールします




== CWMS 5.1 マイナーリリース： Thurs 、 2018 年 7 月 12 日

コンポーネント： 5.1 CWMS ツールおよびサービス： 2018 年 7 月 12 日（木）午後 10 時 30 分東部への影響：エンドユーザ向けの Cloud Workspace デスクトップおよびアプリケーションサービスへのアクセスは中断されません。



=== 5.1 CWMS Web アプリケーション

* グローバルアプリケーションカタログ設定の永続性に関する問題を修正します




== CWMS 5.1 マイナーリリース： Thurs 、 2018 年 5 月 17 日

コンポーネント： 5.1 CWMS ツールおよびサービス 2018 年 5 月 17 日（木）午後 10 時 11 分（ EST Impact ）：エンドユーザ向けのクラウドワークスペースデスクトップおよびアプリケーションサービスへのアクセスは中断されません。



=== 5.1 CWMS Web アプリケーション

* アプリケーションサービスグループのユーザの概要に関する問題を修正します
* データセンターウィザードで、ユーザ名とパスワードが事前に入力された状態で問題を修正します
* データセンターウィザードで、ローカルの VM 管理者およびレベル 3 の技術者のユーザ名の検証を追加します
* セッション処理が改善され、セッションタイムアウト後のユーザの自動ログアウトも可能になりました
* プライマリ管理者が検出できなかった場合は、管理者を削除するときに問題を修正します
* [ データセンター ] -> [ プロファイルサーバー ] のプレースホルダーを [ プロファイル名の入力 ] から [ プロファイル名の入力 ] に変更し、 [ ラベル ] を [ プロファイル名 ] から [ サーバー名 ] に変更します
* AD 管理者がクラウドワークスペース以外のユーザーに対して機能しないように修正しました
* 非クラウドワークスペースの顧客に新しいユーザー / グループを追加できないようにする JavaScript エラーを修正しました
* マスターパートナーがサブパートナーの Active Directory ユーザー管理者を作成できるようにします
* サブパートナーのプライマリ管理者のパスワードリセットを引き起こすバグを修正し、エラーアウトします




== CWS 5.1 マイナーリリース： 2 月、水2018 年 2 月 21 日

コンポーネント : 5.1 CW ツールおよびサービス ( 水曜日、 2 月2018 年 12 月 21 日午後 10 時から 11 時（ EST ）の影響：エンドユーザ向けのクラウドワークスペースデスクトップとアプリケーションサービスへのアクセスは中断されません。



=== 5.1 CW Web アプリケーション

* 問題の管理を管理者アクセスロールで修正しました




=== 5.1 CW ツールおよびサービス

* Workspace で「サービスなし」クライアントをアップグレードするときに、障害が発生したサーバーが自動的に削除されないようにする
* W2016 GPO の更新を処理し、 W2016 VM の RDS セッションにログインしているユーザに通知のポップアップが表示されないようにします




=== 5.1 REST API

* 新しい属性を追加し（新しい属性を使用するように CWS の SPLA レポートを変更）、コアライセンスベースのアプリケーション（特に SQL ）をより適切に処理できるようにする




== CWS 5.1 マイナーリリース： 2 月、水7 、 2018

コンポーネント : 5.1 CW ツールおよびサービス ( 水曜日、 2 月2018 年 10 月 11 日午後 EST の影響：エンドユーザ向けのクラウドワークスペースデスクトップとアプリケーションサービスへのアクセスが中断されることはありません。



=== 5.1 CW Web アプリケーション

* なし




=== 5.1 CW ツールおよびサービス

* 修正 Windows * 2016 での問題アプリロッカーの無効化（ Windows * 2016 問題 * が新たに検出されたため）
* IP がクローン障害イベントに基づいて再割り当てされていない場合に、バグを修正します




=== 5.1 REST API

* Provisioning Collection でサーバを変更するときにストレージタイプを保存する問題を修正しました
* 2 台のターミナルサーバ（ TS ）を使用して Provisioning Collection を作成する場合、収集を検証するために TS サーバを 1 台だけ構築する必要があります




== CWS 5.1 マイナーリリース： 1 月、水曜日2018 年 3 月 31 日

コンポーネント : 5.1 CW ツールおよびサービス ( 次の場合 ) : Wed. 、 Jan2018 年 12 月 31 日午後 10 時から 11 時（ EST ）の影響：エンドユーザ向けのクラウドワークスペースデスクトップとアプリケーションサービスへのアクセスが中断されることはありません。



=== 5.1 CW Web アプリケーション

* トップレベル CWS モジュールのテーブルごとの行数を 10 から 20 に増やします
* ユーザーサポートのみの管理者がクライアントにアクセスできないように修正します




=== 5.1 CW ツールおよびサービス

* テンプレートに .Net Framework v4.5.2 がインストールされていない場合に、サーバーの作成に失敗するというバグを修正しました
* Hyper-V で VM をクローニングするときに問題を修正




== CWS 5.1 マイナーリリース： 1 月、水曜日10 、 2018

コンポーネント : 5.1 CW ツールおよびサービス ( 次の場合 ) : Wed. 、 Jan2018 年 10 月 10 日午後 10 時から 11 時（ EST ）の影響：エンドユーザ向けのクラウドワークスペースデスクトップとアプリケーションサービスへのアクセスは中断されません。



=== 5.1 CW ツールおよびサービス

CWS バージョン 5.1 の Tools and Services （ CW Automation Service 、 VM Automation Service 、 CWAgent サービスを含む）が更新され、特定の RemoteApp アプリケーション配信シナリオで発生する許可エラーがなくなります。具体的には、サービスは次のように変更されます。

* セッションサーバの SSL ワイルドカード証明書の自動展開を、 Remote Desktop （ RD ） Connection Broker サーバおよび Power User サーバにのみ展開するように変更します。ブローカー以外のセッションサーバでは、リモートデスクトップサービス（ RDS ）によって生成されたデフォルトの証明書が使用されます。
* SDDC で Active Directory の外部 DNS 前方参照ゾーンを変更して、クライアント共有セッションサーバの DNS レコードを 1 つだけ作成します。このレコードはクライアントの RDS ブローカサーバー（ VM ）を指し、共有セッションサーバ間のロードバランシングを処理します。パワーユーザサーバには、引き続き別の DNS エントリがあります。


注：この問題は、複数の共有セッションサーバを使用するエンドクライアント設定のみに影響しましたが、この設定を使用して新しいクライアント設定および変更されたクライアント設定を展開します。



== CWS 5.1 マイナーリリース： 1 月、水曜日2018 年 3 月

コンポーネント： 5.1 CW Web App When ： Wed. 、 Jan2018 年 3 月 3 日午後 10 時 30 分（ EST Impact ）：エンドユーザ向けのクラウドワークスペースデスクトップとアプリケーションサービスへのアクセスは中断されません。



=== 5.1 CW Web アプリケーション

* CWS のワークスペースモジュールで、会社コードによるソートを修正します
* 修正 Cloud Workspace ユーザー -> パスワードの強制リセットに変更が反映されない（別のモジュールに移動してからユーザーに戻る場合）
* SDDC 自己展開ウィザード： ThinPrint のインストールを解除すると確認アラートモーダルを追加（ライセンスセクション）




== CWS 5.1 マイナーリリース： Tues. 、 12 月2017 年 5 月

コンポーネント： 5.1 CW Web App When ： Tues. 、 12/2017 年 5 月 10 日から 10 時 30 分（ EST Impact ）：エンドユーザ向けのクラウドワークスペースデスクトップとアプリケーションサービスへのアクセスは中断されません。



=== 5.1 CW Web アプリケーション

* Internet Explorer （ IE ） 11 で CWS Admin MFA エラーを修正
* CWS グループを修正 -> ローカルドライブアクセスが「見つかりません」を返します
* Data Center Self Deploy ウィザード： AzureRM （ ARM ） Azure Active Directory のサポートを追加します
* アプリケーションカタログ：サブスクリプションオプションが常に使用可能であることを確認し、伝播します
* CWS スクリプトイベントモジュール > スクリプトアクティビティ -> アプリケーションの追加：間違ったアプリケーションアイコンパスを修正
* CWS v5.0 にリダイレクトする際にエラーを防止するために、管理アクセス要求の効率を向上します
* AppService の詳細を更新するときや AppService のアプリケーションライセンスを管理するときに発生するさまざまなエラーを修正します
* CWS ワークスペースモジュール > ワークスペースの追加ウィザード -> appservices の修正グローバルコントロールプレーンに誤ったフォーマットが送信されています
* CWS ワークスペースモジュール > ワークスペースの追加ウィザード -> 新規クライアント -> 手順 3 、 JavaScript エラーに対処するために更新グループを修正して更新が処理されていることを確認します




== CWS 5.1 マイナーリリース： Sat. 、 11 月2017 年 11 月

コンポーネント： 5.1 CW Web App When ： Sat. 、 Nov2017 年 11 月 11 日（午後 10 時）午後 11 時（ EST ）の影響：エンドユーザ向けのクラウドワークスペースデスクトップとアプリケーションサービスへのアクセスが中断されることはありません。



=== 5.1 CW Web アプリケーション

* １１月の午後１０時（東部標準時）11 、すべての CWS 5.1 パートナーは、を使用する必要があります https://iit.hostwindow.net[]。この URL は CWS 5.1 （および CWS 5.0 ）をサポートするために改良されています。パートナーは、 CWS 管理者および CWS 管理者アクセスを持つエンドユーザがこの変更を認識していることを確認する責任があります。




== CWS 5.1 マイナーリリース： 10 月2017 年 3 月 30 日

コンポーネント : 5.1 CW Web App および 5.1 CW ツールとサービス ( 次の場合 ) : 月2017 年 10 月 30 日から 23 日の EST への影響：エンドユーザ向けのクラウドワークスペースデスクトップとアプリケーションサービスへのアクセスは中断されません



=== 5.1 CW Web アプリケーション

* CWS Admin MFA ： MFA の送信コードを入力してバグを修正すると MFA コードの再送信が防止される
* SDDC セルフデプロイウィザード： GCP の場合、ディセーブルにするのではなく、ローカル VM 名の管理者を持ってください
* SDDC 自己展開ウィザード : タイムゾーンのドロップダウン幅を拡大します
* スクリプトイベント：スクリプトアクティビティに引数フィールドを追加します
* スクリプトイベント : スクリプト化されたイベントスクリプトの実行時変数として %applicationname% を追加します




=== 5.1 CW ツールおよびサービス

* エンドユーザの E メールアドレス：既存問題のエンドユーザの E メールアドレスが DB に保存されていないことを修正しました
* エンドユーザーのログオンステータス : エンドユーザーのログイン UPN を取得する問題を修正します
* AzureRM のエンドユーザログオンステータス： Azure Managed Disks をサポートしています
* テンプレート : テンプレートが正しく削除されない場合にワークフローを修正します
* リソース：問題を修正し、古いリソースプールを新しい割り当てタイプに変換
* File Audit Report ：ユーザが不明となる原因となるバグを修正します
* Windows 2016 ：エンドユーザワークスペースから PowerShell アイコンを削除する GPO が適切に適用されるように修正
* Change Resources/Resource Allocation Report ：修正エラーが正しく表示されない
* Data Center Resources レポート：使用可能なハードドライブ容量または VM の見積もりを返すようにハイパーバイザーが設定されていない場合、レポートにエラーが表示されないようにします
* Infrastructure Server Monthly reboots ：このサーバのリブートがビジー状態であるため、インフラサーバが CWMGR1 サーバと通信できなかったために、スケジュールどおりに毎月リブートできない場合のシナリオに対処してください




== 5.1 マイナーリリース： Tuees. 、 10 月2017 年 3 月

コンポーネント : 5.1 CW Web App および 5.1 CW ツールとサービス ( 次の場合 ) : Tues...,Oct2017 年 3 月 23 日（東部標準時）午後 10 時から午後 11 時（米国東部標準時）：エンドユーザ向けのクラウドワークスペースデスクトップとアプリケーションサービスへのアクセスは中断されません



=== 5.1 CW Web アプリケーション

* appservices ：問題ブロックの修正 AppService アプリケーションの追加ライセンス機能
* Appservices ： AppService アプリケーションで常に「新しいインスタンスを追加」機能を使用できるようにします
* リソースプールの用語：用語を更新しながら、変更がなくても常にリソースプール構成をサーバに適用可能–「アップデート」を「サーバに適用」に変更し、「編集」を「管理」に変更
* ワークロードのスケジュール： Edit モーダルが常に開いていることを確認します
* ワークロードスケジュール：選択する時間を矢印で常に表示します
* スクリプトイベント：より詳細な時間選択を可能にします
* CWS レポート「管理者アクセス」：問題を修正することで、 IP カラムにクライアント IP だけでなく複数の IP アドレスが表示されるようにしました




=== 5.1 CW ツールおよびサービス

* File Audit Service ：常に無効になりました
* 自動化サービスと新しい SSL ワイルドカード証明書（ RDP 接続）： RDS ゲートウェイ上の更新された RDP 証明書を常にリフレッシュするためのコマンドの更新順序（つまり、キャッシュされない）




== CWS ® 5.1 の初期リリースの概要

Cloud Workspace Suite 5.1 は、 2017 年第 3 四半期からパブリックベータ版に移行しています。このリリースでは、 CWS API と Admin Control インターフェイスの両方が更新されています。このリリースは、 CWS 5.0 （ 2016 年第 4 四半期リリース）のアップデートであり、バージョン 4.x エンティティとの「下位互換性」はありません。

2017 年第 4 四半期に正式にリリースされた後は、 CWS 5.1 への移行に伴うアップグレード料金や導入コストは発生しません。アップグレードは、各パートナーと連携して CloudJumper によって完了し、既存のサービスは中断されません。CWS 5.1 は、以前のバージョンのすべての機能を引き続きサポートし、管理者とエンドユーザの両方のエクスペリエンスを向上させる新機能を拡張し、以前のリリースの Cloud Workspace Suite で導入された受賞歴のある自動化とオーケストレーションをさらに向上させます。

CWS 5.1 のアップグレードは、 CWS 5.0 で導入された最新のアーキテクチャと REST API プラットフォームを拡張して活用することにより、最も高速で簡単なアップグレードです。CWS 5.1 は、 CloudJumper のフレンドリーな環境への取り組みを継続し、外部の開発者が Cloud Workspace に基づいてサービスや製品を拡張できるようにしています。


NOTE: CWS 4.x は 2017 年 12 月 31 日に正式にサポート終了となります。CWS 4.x プラットフォームに参加しているパートナーは、 4.x 導入に関する直接サポートを受けなくなり、 4.x の更新やバグ修正は提供されなくなります。



=== 5.1 主な特長：

* Windows 2016 Server のサポート
* Microsoft Azure Resource Manager のフルスタックサポート
* Office 365 Single Authentication のサポート
* CWS ポータル管理者向けの MFA
* Provisioning Collection Management の改善
* 管理者が自動化とスクリプトを定義しました
* リソース・サイジング管理スキーム




==== Windows 2016 Server のサポート

* サポートされているすべてのプラットフォームで Windows Server 2016 サーババージョンをサポートします。
* Windows 2016 Server は、共有 RDS セッションユーザーに「 Windows 10 」デスクトップエクスペリエンスを提供し、グラフィック集約型アプリケーションの GPU 割り当てなどの構成オプションを可能にします。 *




==== Microsoft Azure Resource Manager のフルスタックサポート

* Microsoft では、従来の暗号化キー / 代理アカウントユーザエンタイトルメントモデルから Azure Resource Manager モデルへの移行が必要です。
* Microsoft Azure Resource Manager は、ユーザが解決策内のリソースをグループとして操作できるようにするフレームワークです。
* 必要な認証属性は、 Software Defined Data Center （ SDDC ）の導入時に 1 回収集され、再入力や再認証なしで他の Microsoft Azure アクティビティに再利用されます。




==== Office 365 の単一認証のサポート

* Microsoft Office 365 では、新しいコンピューターやデバイスで Office 生産性スイートを使用するたびに、エンドユーザーが資格情報を入力する必要がある認証モデルを使用します。
* CWS 5.1 では、これらの資格情報をサーバファーム全体で管理して、エンドユーザが新しい Office 365 サブスクリプションを初めて使用したときにのみ認証を要求できるようにします。




==== プロビジョニング収集管理の改善

* 事前定義済みのワークロード用のハイパーバイザーテンプレートの設定と管理は、特に複数のハイパーバイザープラットフォームで作業する場合に混乱を招く可能性があります。
* CWS 5.1 は、既存のテンプレートまたはクラウドプロバイダの VM イメージに基づくサーバインスタンスの作成を含む自動ハイパーバイザ管理機能を導入します。 CWS Web App からアプリケーションをインストールするために、作成したサーバに直接接続 / ログインします。 設定済みのサーバインスタンスからの自動テンプレート作成 / Windows sysprep 、アプリケーションパスの検証と CWS 内からのインストールを実行して、ハイパーバイザーやクラウドサービスダッシュボードに直接アクセスする必要を排除します。




==== CWS ポータル管理者向けの MFA

* CWS 5.1 には、 CWS 管理者専用の組み込み多要素認証（ MFA ）解決策が含まれています
* パートナーはエンドユーザ向けに独自の MFA 解決策を実装できます。人気のあるオプションとしては、 Duo 、 Auth-Anvil 、 Azure MF などがあります。CloudJumper は、 2018 年第 1 四半期にエンドユーザ向けに独自の組み込み MFA をリリースする予定です




==== 管理者が定義した自動化

* CWS は、管理者が定義したタスク / スクリプトの実行の自動化により、サービスプロバイダの導入 / 管理の自動化を改善します。
* この機能強化により、 CWS 5.1 は導入の大幅な高速化、管理の簡素化、オーバーヘッドコストの削減を実現します。
* CWS 管理者定義の自動化により、イベントに基づいたアプリケーションのインストールまたはアップグレードが可能になり、パートナーはこの方法を使用してアプリケーションの自動インストール / メンテナンスを開始できます。




==== リソースのサイジング管理スキーム

* CWS 5.1 リソース機能は、 3 つのリソーススキーマを追加することで、リソースを動的に拡張する機能を強化します
* 既存の Total Users スキーマが、さらに 3 つのリソースサイジングスキームによって拡張されました。つまり、 Fixed 、 Active User 、および Activity-based です
* 例：固定メソッドは、 CPU と RAM の正確な仕様をサポートします。
* すべてのリソースサイジングスキームでは、即時 / 強制的な変更や夜間の自動リソースチェック / 変更が引き続き可能です。

