= 概要




== 概要

アプリケーションエラーのトラブルシューティングは 'VDS 自体を使用しない一般的な管理方法ですが 'VDS と管理者に提供する制御レベルによって大幅に支援されますネットアップの VDS はお客様向けの問題のトラブルシューティングではありませんが、以下に示す基本情報を特定したあとで管理者にアドバイスすることで、エンドユーザやサードパーティによる詳細な調査やトラブルシューティングを実施できます。

* 問題を体験しているユーザの名前
* ユーザが作業していたアプリケーションの名前
* ユーザーのセッションが行われたサーバー
* 問題を再現する手順




== ツールのレビュー



=== 監視

ユーザーが使用していたサーバーを特定したら、モニタリング解決策を調べて、リソース（ CPU および RAM ）の消費量が正常なレベル内であることを確認します。また、アプリケーション固有の要件（原因が実行されていない場合に問題となる特別なサービス）が機能していることを検証することもできます。このような状況では、前述のサービスのアップ / ダウン監視などの高度な設定がトリガされた可能性があります。



=== ウイルス対策

サーバと Azure Active Directory の両方にアクセスできる管理者は、何が検出され、どのポリシーが設定されているかを確認できます。予期しない事態が発生した場合は、アプリケーションに影響を与える可能性があります。



=== その他のツール

アプリケーションによっては、無期限にログインしたままのサービスアカウントや、物理的な機器（たとえば、オンサイトのネットワークアプライアンスや製造機器または診断ユーティリティ）への VPN など、追加のコンポーネントが必要になる場合があります。このような場合、アプリケーション固有のエラーは、アプリケーションのインストール方法や設定方法以外の原因で発生する可能性があります。



=== 第三者へのアクセスの拡張

アプリケーションやそのデータベースは、多くの場合、ソフトウェアベンダー（ ISV ）自身またはそのソフトウェアの構成、管理、統合に関するサードパーティのエキスパートによってインストール、構成、サポートされます。このような状況では、一時的な管理アクセスを次の手順に拡張する必要があります。 link:Management.System_Administration.provide_3rd_party_access.html["第三者への一時的なアクセスの提供"]

アップグレードまたは更新が完了したあと、または問題が解決したあとに、これらのサードパーティアカウントをシャットダウンすることを推奨します。

多くの場合、このレベルのトラブルシューティングでは、 ISV とのソフトウェア保守契約が必要になります。これが適切でない場合、 ISV はこれが実施されるまでサポートしません。


NOTE: 問題のトラブルシューティングは、ハードウェア（デスクトップ、ラップトップ、シンクライアントなど）のエンドユーザと連携している可能性もあります。たとえば、ユーザーのラップトップをアップグレードすると、シンクライアント構成ファイルの目にマシンがロックされ、エンドユーザーが仮想デスクトップにログインできるツールにアクセスできなくなる可能性があります。この場合、製造元がサポートする前に、ハードウェアの保守契約が必要になることがあります。
